### ISSUE TITLE
Inconsistencies with theme colors 

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode-hexeditor#10]
Testing https://github.com/microsoft/vscode/issues/98980

Looks like the select box for endianness and the data inspector selection outline is not a color from the theme.

![image](https://user-images.githubusercontent.com/8235156/83548948-87ffd800-a4d2-11ea-85bb-9c90ad88c402.png)

![image](https://user-images.githubusercontent.com/8235156/83549205-f3e24080-a4d2-11ea-8595-e69b71db4af9.png)

Repro:
- changing themes doesn't change colors

**Comment by lramos15** [comment]
Outline has been fixed in #39. You cannot change the blue highlight as that's an OS specific native element. The only way would be to make my own if we desperately wanted to solve that problem.
