### ISSUE TITLE
Hex editor scrolling feels non-native

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-hexeditor#101]
Testing https://github.com/microsoft/vscode/issues/103176

When I scroll through the hex editor with the macbook touchpad, it feels "off" in a way that's hard to explain. I think the main issue is that the speed of the scroll is much slower than the speed that a normal page would scroll. Like it's scrolling rows at a constant speed and not respecting a "flick" on the touchpad.

**Comment by lramos15** [comment]
I think it's a challenge with custom scrolling. I made it so each mousewheel event scrolls one row. The trackpads flick is just firing a bunch of mousewheel events which causes it to scroll a couple of rows. It does this one row at a time giving it that "artificial" feel. I'm not sure the best way to fix the scrolling as I think it's part of a bigger problem of my custom virtualization see #5

**Comment by roblourens** [comment]
You should get a property like `wheelDeltaY` or something that gives you a magnitude for the scroll event, and use that to scroll more or fewer rows. Would take some experimentation to get it to feel right, or we can check how it's done for the editor.

**Comment by Tyriar** [comment]
There is also `MouseEvent.deltaMode` which you need to respect to get track pads working right.

**Comment by connor4312** [comment]
We since do use native scrolling and update the hex editor byte display using native scroll location.
