### ISSUE TITLE
Can't switch focus from left/right easily

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-hexeditor#103]
- Click to focus something on the left
- Click the highlighted box on the right to move focus there
- It toggles to unfocus the pane on the right and I have to click a second time 

I shouldn't be able to unfocus the thing by clicking on it. Also I can't tab between the left and right panes

**Comment by lramos15** [comment]
The click to focus appears to have fixed at some point. As for the tabbing. Do you expect that when you're at the last cell and hit tab it jumps to the right? Right now I use the arrow keys for in editor navigation and haven't really considered how tab works

**Comment by roblourens** [comment]
I think I'd expect tab to move focus from the left pane, to the right pane, to the data inspector
