### ISSUE TITLE
Improve partial results messaging

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-hexeditor#106]
Testing https://github.com/microsoft/vscode/issues/103176

![image](https://user-images.githubusercontent.com/323878/88318738-0b1dfd00-ccd0-11ea-9779-e995c8f55cee.png)

What does this mean? You are only showing me one result at a time so how can there be too many matches?

**Comment by lramos15** [comment]
Results aren't streamed back, they're sent back all at once. To reduce the load on the webview / extension host we cap matches at 10,000.

**Comment by Tyriar** [comment]
Don't you only search for the next match? I don't see feedback on other search results in the view?

![image](https://user-images.githubusercontent.com/2193314/88419028-505a3180-cd99-11ea-8d19-74db3a1c4252.png)

Ok it seems like you're searching for all matches as find next is quick afterwards, and I'm guessing this is why the search takes so long? It would probably be a better experience to only search for the next match when asked. Alternatively showing the "x of y" like the text editor does would clarify what partial results mean (I think the editor does this by saying "x of ?").

**Comment by connor4312** [comment]
We now show a link in the editor. Clicking on the link will load all results. Additionally, results are now streamed back:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/2230985/206590005-8ca56d13-336f-4e83-bd32-c4f383867fcf.png">
