### ISSUE TITLE
Collapse away the replace box

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-hexeditor#109]
Testing https://github.com/microsoft/vscode/issues/103176

I think it would look a little cleaner to expand/collapse the replace box, like it works in the other find inputs in vscode. Search will be used much more often than replace

**Comment by lramos15** [comment]
This was discussed a bit and I initially suggested it, but it might feel super cluttered trying to fit a collapse chevron in there. cc @misolori

**Comment by misolori** [comment]
I think that could work:

![image](https://user-images.githubusercontent.com/35271042/88337224-33672500-cceb-11ea-872a-63a0acf54316.png)

**Comment by connor4312** [comment]
This now works identical(ish) to core's find widget

<img width="394" alt="image" src="https://user-images.githubusercontent.com/2230985/206590102-83a2252c-02e5-4e78-969c-3162099babf2.png">
