### ISSUE TITLE
Pressing alt hides the search error message

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-hexeditor#114]
Testing https://github.com/microsoft/vscode/issues/103176

macOS

- Search with an invalid regex, get the red popup error
- Press alt (like to move with alt+arrow)
- The error disappears, no clue why that would happen

**Comment by lramos15** [comment]
Fixed by https://github.com/microsoft/vscode-hexeditor/commit/44f6f609e888c8735a76306d7a83017b9bdd9a90
