### ISSUE TITLE
Text replace feels weird without the ability to delete or insert

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-hexeditor#115]
Testing https://github.com/microsoft/vscode/issues/103176

Replace, especially the regex replace, seems very difficult to use when I don't have the ability to delete characters or insert characters into the file. Replace is not "replacing", it's overwriting the match character by character and either leaving part of the match in place, or losing part of the replacement string, if it stops early. It's not actually clear when this would be useful to me vs using the normal text editor. The hex replace is fine, it makes sense to be able to search for a specific string of bytes then replace it with another string of bytes.

**Comment by lramos15** [comment]
I agree that it can't mirror the editor exactly. I also understand that insert cells in the middle would be a beneficial feature to implement eventually. I think hex replace is much more useful and text replace is just there so both sides feel mirrored.

**Comment by roblourens** [comment]
Yeah, I guess I don't know what I am asking for here. The feature doesn't feel very useful, but I don't think we should get rid of it.

**Comment by lramos15** [comment]
Since this sounds like https://github.com/microsoft/vscode-hexeditor/issues/71 would be the resolution to this problem, I'm going to close this in favor of tracking it there. It seems like the addition of insertion and deletion at arbitrary locations would fix the problem.
