### ISSUE TITLE
"Cannot read property 'previousValue' of undefined" while editing

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-hexeditor#120]
Testing https://github.com/microsoft/vscode/issues/103175

**repro**
1. Start quickly editing a hex file (not sure exactly what triggers this)

**bug**
See the following exceptions in the webview:

```
editHandler.ts:116 Uncaught (in promise) TypeError: Cannot read property 'previousValue' of undefined
    at EditHandler.editAscii (editHandler.ts:116)
    at async VirtualDocument.keyBoardHandler (virtualDocument.ts:404)
```﻿
​

**Comment by lramos15** [comment]
Do you know what exactly you were doing besides quickly editing. I can't seem to repro this.

**Comment by lramos15** [comment]
Unable to reproduce for now, please reopen the issue if you see it again :)
