### ISSUE TITLE
Keyboard interface of find widget inaccessible

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-hexeditor#123]
![image](https://user-images.githubusercontent.com/8586769/88356909-49daa400-cd1e-11ea-8c7e-fb8b328432c3.png)
Not clear how to focus the next button with keyboard. Also, not clear what the keyboard shortcut for next is? This could be added in the title, for instance in the editor the title is "Next match (enter)". Also is there a reason we aren't using the same shortcut (enter)? Currently it triggers a search, but we tend to just do that live in other parts of the editor (command palette, extensions, in-editor find, workspace search).

Also, here:
![image](https://user-images.githubusercontent.com/8586769/88357068-d2f1db00-cd1e-11ea-9a7f-0fd6ecd7c6f5.png)
the toggles are not tabbable.

**Comment by lramos15** [comment]
I think some improvements were made after this issue was filed, but this would be a further improvement on that.

**Comment by connor4312** [comment]
Fixed with my find widget revamp
