### ISSUE TITLE
Lots of console errors when moving quickly through find results

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-hexeditor#125]
![image](https://user-images.githubusercontent.com/8586769/88357411-05e89e80-cd20-11ea-838a-67ebe96323ae.png)

I think this tends to happen if I click the next button while the page is loading.

**Comment by lramos15** [comment]
I'm clicking the button as fast as possible and I cannot reproduce this. Do you have a gif or better repro steps. Does it only happen on a specific file?

**Comment by JacksonKearl** [comment]
Cant reproduce anymore. I'll open a new issue if I see it again.
