### ISSUE TITLE
Decoded text column cut off

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-hexeditor#13]
Testing https://github.com/microsoft/vscode/issues/98980

![image](https://user-images.githubusercontent.com/876920/83552625-e753ed00-a4be-11ea-9008-dae16faef8ae.png)

The decoded text column is cut off at the right boundary.

**Comment by rebornix** [comment]
it turns out to be the window is narrow, maybe we want to scroll horizontally a bit to show the text

![image](https://user-images.githubusercontent.com/876920/83552752-2124f380-a4bf-11ea-8715-5725ededd057.png)

**Comment by lramos15** [comment]
There's a horizontal scroll bar when the editor doesn't fit. Did you expect something different?
