### ISSUE TITLE
Don't change text input background and use correct focus border

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#133]
Testing microsoft/vscode#103174

They use a subtle (depends on theme) background change and the focus border does not respect the theme's key:

![recording (8)](https://user-images.githubusercontent.com/2193314/88414593-f609a280-cd91-11ea-955f-712219b21180.gif)

**Comment by lramos15** [comment]
Do you have any themes that have a more prominent background change? I don't see any background change on this theme in the editor.

**Comment by Tyriar** [comment]
This got fixed with the focus key fix.
