### ISSUE TITLE
A single hex character should be a valid hex search

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#134]
Testing microsoft/vscode#103174

![image](https://user-images.githubusercontent.com/2193314/88414686-1cc7d900-cd92-11ea-9f0d-832dc061d55b.png)

This should just search for `0a` implicitly. It leads to a really bad experience:

![recording (9)](https://user-images.githubusercontent.com/2193314/88414760-3832e400-cd92-11ea-9fcb-8ba35e8d9f3a.gif)

**Comment by lramos15** [comment]
I guess this would help with the invalid query message, but it feels weird to me to edit the user's query like that.

**Comment by Tyriar** [comment]
Edit? If a user wants to search for `a`, why would you stop them? It seems most likely that a user would want to search for `0a`, `01`, etc. when just using a single character. This also applies to an odd number of characters: `01 02 3` should search `01 02 03`. Of course if there is prior art here we should consider that.

**Comment by lramos15** [comment]
Ok. This seems to match other hex editors, so I will add that. It should greatly reduce the invalid query messages too
