### ISSUE TITLE
Search errors should be an overlay like the search view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#136]
Testing microsoft/vscode#103174

They're not consistent:

![image](https://user-images.githubusercontent.com/2193314/88414890-70d2bd80-cd92-11ea-85ca-db3bfd102691.png)

![image](https://user-images.githubusercontent.com/2193314/88414936-80520680-cd92-11ea-9f29-e822965975f9.png)

**Comment by lramos15** [comment]
On top of this issue, the message box also stays when focus has left the find widget which isn't the case in VS Code

**Comment by connor4312** [comment]
Fixed in editor revamp
