### ISSUE TITLE
Search does not match the find widget's styles

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#137]
Testing microsoft/vscode#103174

Problems:

- No border around toggled options
- Background/focus border around input https://github.com/microsoft/vscode-hexeditor/issues/133
- Font appears to be different

![image](https://user-images.githubusercontent.com/2193314/88415059-b5f6ef80-cd92-11ea-944a-20b2ae02a39b.png)

![image](https://user-images.githubusercontent.com/2193314/88415000-9e1f6b80-cd92-11ea-849e-1d79bd9ee22f.png)

**Comment by connor4312** [comment]
We now match just about identically
