### ISSUE TITLE
Data inspector shows invalid after double clicking a hex value

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-hexeditor#14]
Testing https://github.com/microsoft/vscode/issues/98980

![image](https://user-images.githubusercontent.com/876920/83553713-77466680-a4c0-11ea-8a03-1703dffecfa6.png)

* Click a hex cell
* Click again
* The data inspector shows invalid

**Comment by lramos15** [comment]
This is the "blank state" and what I intended to happen. Should I just make them blank?

**Comment by StefanoCecere** [comment]
> This is the "blank state" and what I intended to happen. Should I just make them blank?

i think it would be much better. unclickable empty fields

**Comment by lramos15** [comment]
I believe that invalid makes it sound like something is broken so I have taken your suggestion as I feel it provides a better user experience. Thanks 👍
