### ISSUE TITLE
Selection/focus can go into a broken state

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#140]
Testing https://github.com/microsoft/vscode/issues/103174

I got into this state by selecting a bunch of cells (drag+drop) and clicking around a bit

![image](https://user-images.githubusercontent.com/2193314/88414053-1ab14a80-cd91-11ea-99f2-92571da55143.png)

The blank cells appear to be a bug

**Comment by Tyriar** [comment]
![recording (11)](https://user-images.githubusercontent.com/2193314/88416323-dde75280-cd94-11ea-9fc5-5e73e0304eae.gif)

**Comment by lramos15** [comment]
This was intentional, but has since been fixed by #92
