### ISSUE TITLE
Scrolling by dragging the scroll bar drops a lot of frames

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#143]
Testing microsoft/vscode#103174

![image](https://user-images.githubusercontent.com/2193314/88416769-9ca37280-cd95-11ea-90c5-bf0b310a34ac.png)

**Comment by lramos15** [comment]
I think this has to do with my virtual scroll widget not being the best. It's definitely a debt which I would like to fix at some point as I believe it's the biggest performance hit the editor currently has.

**Comment by Tyriar** [comment]
That's one of the problems, the redo above is also taking like 150ms to perform there.

**Comment by connor4312** [comment]
This appears to be at least better with the editor rework
