### ISSUE TITLE
Partial results warning is confusing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#147]
Testing microsoft/vscode#103174

I see this only after clearing a search in a big file:

![image](https://user-images.githubusercontent.com/2193314/88417864-8e565600-cd97-11ea-870a-c3b09b850402.png)

How are partial results possible when search success is binary?

**Comment by lramos15** [comment]
What do you mean search success is binary? We cap results at 10,000 so if there were more than 10,000 results you should see this message. I'm not sure why you're seeing this after you clear a query. Is this the same ask as https://github.com/microsoft/vscode-hexeditor/issues/106?

**Comment by Tyriar** [comment]
Yes it's the same.
