### ISSUE TITLE
Don't search on type

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#148]
Testing microsoft/vscode#103174

This is super slow and unexpected imo.

![recording (16)](https://user-images.githubusercontent.com/2193314/88418007-c2317b80-cd97-11ea-985c-0016770775c7.gif)

**Comment by lramos15** [comment]
This is what VS Code does right now. What would you suggest the improvement be, I had a search button before and it was ill received. I think an enhancement might be to debounce the key up so it's only when you've stopped typing for say 100ms that we search

**Comment by Tyriar** [comment]
You're right, the difference here is that the file can be gbs though. Also even in the relatively small file (2276kb) I was testing the search is instant in the text editor but took seconds in hex editor.

**Comment by lramos15** [comment]
I think parallelizing search would be a decent improvement as well. Right now it's just a double for loop through the whole file which gets pre-empted often to check for cancellation making it slow.

**Comment by connor4312** [comment]
Searching is now done in the extension host, and is pretty fast. We also do debounce the search request, and support cancellation. I don't see this issue any longer, but let me know if you still hit it.
