### ISSUE TITLE
Search returned an error!

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#149]
Testing microsoft/vscode#103176

![image](https://user-images.githubusercontent.com/2193314/88430394-3cb8c600-cdad-11ea-8f58-0d3aeb493828.png)
Renderer:
![image](https://user-images.githubusercontent.com/2193314/88430477-5b1ec180-cdad-11ea-9b63-50ba048459d2.png)
Webview:

![image](https://user-images.githubusercontent.com/2193314/88430504-696cdd80-cdad-11ea-848e-16c9130b6f0b.png)

**Comment by lramos15** [comment]
Search has been re-implemented this should no longer be the case please let me know if you run into any issues still
