### ISSUE TITLE
Scrolling with a trackpad or arrow keys makes the editor blank

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode-hexeditor#15]
Testing https://github.com/microsoft/vscode/issues/98980

Scrolling really fast with a mouse looks ok, but if I scroll too much with a touchpad or keep the arrow key pressed, the editor goes blank. I'm guessing this has something to do with how events are debounced?

Touchpad:
![touchpad](https://user-images.githubusercontent.com/8235156/83554564-02345a80-a4db-11ea-9bcf-7f973a6f077b.gif)

Keyboard:
![keyboard](https://user-images.githubusercontent.com/8235156/83554662-209a5600-a4db-11ea-8433-f3a97c8918c7.gif)

**Comment by lramos15** [comment]
Similar to #5, so I'm going to close this one and use #5 to track both issues.
