### ISSUE TITLE
Losing search / replace strings when switching editors

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-hexeditor#158]
Testing https://github.com/microsoft/vscode/issues/103176

Switching back and forth between the hex editor and some other editor lets the search and replace strings and any enabled modifiers disappear.

**Comment by lramos15** [comment]
We currently do not persist these. To do this you would utilize the WebviewStateManager similar to how it's used for selection and scroll position.

**Comment by eugene-shcherbo** [comment]
Realized that we can trigger a search request (which when completed will select found items in the editor) and then we can select random text manually. What should take a priority after tab switching - search selection or random manual selection? As you can see from gif it gives priority to a search selection. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/23394756/95356612-88204200-08cf-11eb-892d-8a6e7995b994.gif)

**Comment by connor4312** [comment]
This no longer happens.
