### ISSUE TITLE
Missing padding inside the data inspector

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode-hexeditor#16]
Testing https://github.com/microsoft/vscode/issues/98980

Maybe add some padding where the actual data is shown? (padding around `110` for `Int8` for example)

cc: @misolori thoughts?

![image](https://user-images.githubusercontent.com/8235156/83568060-9a890a00-a4f0-11ea-9d40-98c7f288e9ae.png)

**Comment by misolori** [comment]
I do think adding some padding will help make the table breathe a bit. I'd probably add 4-8px to the left and right side.

**Comment by lramos15** [comment]
Fixed via https://github.com/microsoft/vscode-hexeditor/commit/af0fba4b92739e4bb25a0dcb4961811facaaf1c7
