### ISSUE TITLE
Unexpected "line breaks" in Decoded Text column when used with Cascadia Code font

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode-hexeditor#160]
Extension version: 1.1.0
Version: 1.48.0-insider (user setup)
Commit: 15e798e081984a17eae00de91adf4479190d5ed2
Date: 2020-07-28T10:39:18.007Z
OS: Windows_NT x64 10.0.18363

**Font settings:**
```
"editor.fontFamily": "'Cascadia Code PL', Consolas, 'Courier New', 'Segoe UI emoji', monospace",
"editor.fontSize": 14 // default
```

**File content:** `111-111-111-111-222-222-222-222-333-333-333-333-444-444`

**Expected behavior:** Decoded text has 4 lines like
```
111-111-111-111-
222-222-222-222-
333-333-333-333-
444-444+
```

**Actual behavior:**
![image](https://user-images.githubusercontent.com/1312662/88696872-77ec2980-d10c-11ea-8c04-402aae65a4bf.png)

Depending on content it might break after `-`, space etc.

After playing some time with styles and settings:
* Changing `padding: 4px;` to `padding: 3px;` for `#ascii > .row > span` renders lines as expected.
* Adding `display: inline-block` for `#ascii > .row > span` renders lines as expected (but leads to different vertical padding behavior).
* Changing width for `rowwrapper` from `259px` to `260px` renders lines as expected (I guess this calculation is root cause for rowwrapper being too narrow to fit all cells, probably rounding up or adding 1px should help).
* No effect when I change `font-weight`.
* No effect when I change `"window.zoomLevel"` setting (with default `"editor.fontSize"`).
* Changing `"editor.fontSize"` renders lines as expected for different combination of  `"editor.fontSize"` and  `"window.zoomLevel"`. (Looks like 16 and 20 works best across different zoom levels)

**Comment by lramos15** [comment]
The latest insiders switched to electron 9 which enabled chrome's new layout engine. This broke the decoded text section as you're seeing now. I plan to release tomorrow morning and the release will include this fix which is already in master (the fix that I used by the way is the third one you described), ultimately there is still an issue here as the one pixel extra shouldn't be needed but it works and is barely noticeable. Thanks for reporting!
![image](https://user-images.githubusercontent.com/4544166/88701052-81a76a00-d0d7-11ea-92c3-b4ebf68861c7.png)

**Comment by IllusionMH** [comment]
Thanks! I tried to search for duplicates but had no luck with them.
Glad that it's fixed.
