### ISSUE TITLE
Use localhost url's as an API to get and set

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-hexeditor#163]
First, I think support for binary templates would be great, which is requested here for example
https://github.com/microsoft/vscode-hexeditor/issues/50

But also a way to talk to the hex editor would be a great addition to that. I have been thinking of what would be a good way. 
Here are some thoughts:

- It should be language agnostic so everyone can stay in their comfort zone programming language without the need of getting familiar in a specific language.

- It should be easy to use, no complex setups etc. For example, don't require setting up a sockets. That will make the barrier to use it so much harder (UDP vs TCP etc.).

In almost every language it is easy to load a file from a url, I think that should be leveraged.
To give an example of how we could talk to the vscode HexEditor:

```
localhost:8899/hexeditor/get?file=%2Fdata%2Fdump%2Fout.hex&mem_offset=160&n_bytes=4
```

To set "vscode" at adress `1E0`

```
localhost:8899/hexeditor/set?file=%2Fdata%2Fdump%2Fout.hex&mem_offset=1E0&content=7673636f6465
```

Please don't make JSON the base layer of the API. JSON should be on top of the base layer. It's a horrible format to work with in a lot of languages. Also, I think a lot of people work with binary files cause they care about speed and file sizes. Json is a step in the wrong direction for people who care about speed and file size.

Of course the two url's I propose above are just the beginning. There should be things like telling VSCode that from adress x to y, everything should be set as Float 32 for example.

To confirm setting something went correct a id could be passed that the user can generate themself (counting up will do):

```
localhost:8899/hexeditor/set?confirm_id=456&file=..........
```

To check if above went correct:

```
localhost:8899/hexeditor/get/confirm_correct_set?confirm_id=456
```

The next steps would be telling vscode that adress x is a Float 32 etc.

**Comment by lramos15** [comment]
I don't think I understand what you'r asking for here. It sounds like you want the hex editor to spin up a local web server and then have that be a hex api of sorts?

**Comment by NotWearingPants** [comment]
Umm, HTTP uses TCP sockets btw.

Why is a server the right thing here? It seems like what you're looking for simply a library.

**Comment by lramos15** [comment]
I'm going to close this as out of scope as it sounds like writing a web adaptor on top of the hex editor. The ideal solution would be expose an API for the hex editor and then you write a web adaptor on top.
