### ISSUE TITLE
Suggestion: change display name to 'Hex Editor'

### ISSUE THREAD

**Issue by GustavoASC** [microsoft/vscode-hexeditor#166]
Hello my friends,

I noticed that the display name of this extension, on Marketplace, is 'HexEditor' without space character between 'Hex' and 'Editor'. I believe this can lead to some difficulties while looking for the extension. In my opinion, typing 'Hex Editor' is more intuitive than 'HexEditor'.

I suggest we change the display name of the extension adding a space character between these two words, which can be safely done since it does not break anything on Marketplace. It's not related to extension ID nor anything similar.

Here is what currently happens when you type 'hex editor' on Marketplace search:

![hex editor type](https://user-images.githubusercontent.com/10179520/89051796-266db580-d32b-11ea-9b33-ccff21e4f11b.gif)

I can make the PR with this change if you guys agree.

**Comment by tommai78101** [comment]
If you're going to change the name, can you also make it be "Microsoft Hex Editor"? I think it would aptly describe what this extension is.

**Comment by lramos15** [comment]
I discussed this with my team the other day as this is something that I realized as well. I have renamed it to "Hex Editor". @tommai78101 I don't think we need to say Microsoft Hex Editor because the publisher is Microsoft and therefore it already carries that verbosity in the viewlet.
