### ISSUE TITLE
Add the ability to edit and save files

### ISSUE THREAD

**Issue by 06needhamt** [microsoft/vscode-hexeditor#17]
I know this is only the initial version but I would like to have the ability to edit and save files from within this extension.

**Comment by lramos15** [comment]
This in the end goal, for now we're just trying to get the initial hex viewing and navigation experience solidified so that it isn't awful come time for editing to be implemented.

**Comment by cwmoriarty** [comment]
Why is this called a hex editor if you can't use it to edit in hex?

Maybe call this fundamental fact out in the extension description?

**Comment by lramos15** [comment]
@cwmoriarty I'm working diligently to get some basic editing support implemented which will ship in the next iteration. The name HexEditor was chosen as it will support hex editing very soon and was released early to provide feedback on the UI / UX prior to implementing editing. There has always been a note at the very top of the README stating it currently does not support editing.
