### ISSUE TITLE
Selecting end of file shows 00000NaN

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#172]
![image](https://user-images.githubusercontent.com/2193314/89799207-fe781200-dae1-11ea-963e-d618a7f19d3f.png)

**Comment by Tyriar** [comment]
Our savior! 🎉

**Comment by jeremy-rifkin** [comment]
I was so confused why the hex editor was showing this weird "+" 00000NaN thing at the end of my file. I should have realized sooner it was just a placeholder. It would be great if this was documented.

**Comment by Tyriar** [comment]
@jeremy-rifkin it was a bug, it should hopefully go away in the next release.

**Comment by jeremy-rifkin** [comment]
@Tyriar Ah, thank you!
