### ISSUE TITLE
Automatic Opening Option

### ISSUE THREAD

**Issue by jsilvermist** [microsoft/vscode-hexeditor#173]
It would be great if there was an option to enable/disable automatically opening the file with the Hex Editor when you open a binary file and it would normally say "The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?".

**Comment by lramos15** [comment]
There's the ability to specify the hex editor for certain file types via a glob pattern as shown in the README. I think it becomes difficult in the binary case to know what the user wants when certain binary files would benefit from different custom editors that aren't the hex editor. Right now there is the ability to click the do you want to open anyways and be prompted with your custom editor which helps a lot, but isn't the automatic option you're looking for.

**Comment by jsilvermist** [comment]
For me the main use-case is dealing with many extension-less binary files in a single project, and every time I have to remember to right click and select "open with". 

If "open anyways" would open the hex editor it would be better at least, and that's why I said it could be an option like the following since you never know what some people may want to choose:

- [x] Automatically open unknown binary files with Hex Editor

With this option either bypassing the "open anyways" screen entirely, or at least opening the hex editor once you click past it.

Clicking open anyways doesn't help since it just gives the following without opening the hex editor:
![image](https://user-images.githubusercontent.com/10246291/90085014-e4f2e800-dce4-11ea-8307-6717319114bb.png)

**Comment by lramos15** [comment]
Doin some issue cleanup. Right now making it the default for binary files is not possible without support from VS Code core. However, clicking open anyways should bring a picker up that allows for selecting hex
