### ISSUE TITLE
Feature: Show cursor hex position and decimal position

### ISSUE THREAD

**Issue by uselessscat** [microsoft/vscode-hexeditor#183]
Hi, I wonder if it is possible to show the decimal position of the cursor or the first selected byte of the cursor. This is because if If want to go to x (decimal) bytes position, I have to use external calculator to add or substract hexadecimal values (I believe that ordinary humans are not usually good with hexadecimal numbers)
 
I think this can be added to data inspector section. 

Thanks for this great extension ^.^

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-hexeditor/issues/86
