### ISSUE TITLE
Command namespace should be "Hex Editor"

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#184]
That's the extension name, plus including space or not should find the command if it has a space in it. This is what you get now:

![image](https://user-images.githubusercontent.com/2193314/92742921-eee42700-f334-11ea-84ed-a1824c63e836.png)

**Comment by GustavoASC** [comment]
I believe it's a simple change on package.json, so I'm making a PR to solve this issue. Hope it helps :smiley:
