### ISSUE TITLE
[Suggestion] Alternate character encoding schemes

### ISSUE THREAD

**Issue by DumbGameMaker** [microsoft/vscode-hexeditor#187]
# Alternate character encoding schemes 

Basically being able to switch between things like CP437 and Windows-1252 and UTF-8 and ISO-8859-x.
Suggesting this because I was making ascii art (yes, I know there are a trillion better tools for art than a code editor) and found out that 0xC9 was É and not ╔ like I was looking for. A config option to change the character encoding scheme would be great.

**Comment by pnvnd** [comment]
I would love to see an option to see `DECODED TEXT` in Shift-JIS.  Better yet, an option where we can load a .TBL file or a .JSON file with our own encoding.  For example, maybe an option to load .TBL file that has the following:
```
9B4D=魔
9B4E=神
9B4C=剣
```
So any time you see 9B 4D 9B 4E 9B 4C in the hex editor, it should show 魔神剣 on the `DECODED TEXT`, similar to WindHex32.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-hexeditor/issues/186
