### ISSUE TITLE
Copy Hex data from binary file and format to C code

### ISSUE THREAD

**Issue by Atom2004** [microsoft/vscode-hexeditor#189]
After select the hex data segment from a binary file.
![image](https://user-images.githubusercontent.com/22042246/94353508-6d1a2a80-00a4-11eb-98a0-d3e75752b87b.png)
I want to copy and past it into c code such as
![image](https://user-images.githubusercontent.com/22042246/94353526-ab174e80-00a4-11eb-9b3d-f306967b70cd.png)

**Comment by mjbvz** [comment]
Closing as out of scope for this extension since it is language agnostic. A C extension could do this transform on paste though if it detects that you've copied hex data
