### ISSUE TITLE
Can't open any file in hex editor

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-hexeditor#19]
Testing https://github.com/microsoft/vscode/issues/98980

1. Create `empty` file

I can't find any way to open this file with the hex editor. I've tried Command Palette, right click... the `Open With` or `Reopen With` options are nowhere to be found.

**Comment by lramos15** [comment]
Glob pattern was expecting a file extension. You can now open them, but they don't look pretty see #18
