### ISSUE TITLE
Add way to "Go to offset"

### ISSUE THREAD

**Issue by blacktop** [microsoft/vscode-hexeditor#191]
A key combo that pops a text entry modal to enter an offset in the file to jump to OR an editable text box that always has the current offset and if you change it it updates to that new offset (given it's valid) ? 🙏

**Comment by blacktop** [comment]
It would also be amazing if there was a way to Goto address in a debug session's local variable value by right clicking on it and having the file's current offset change to that?? 🤯

**Comment by englercj** [comment]
+1 scrolling to find the offset manually is difficult, this feature would be fantastic. Reusing the normal Ctrl+G 'go to line' key seems reasonable.

**Comment by ozkl** [comment]
A must have feature when a particular address needs to be found in a megabytes of size file.
