### ISSUE TITLE
Paste hex (and text).

### ISSUE THREAD

**Issue by jtagcat** [microsoft/vscode-hexeditor#192]
Interaction with a clipboard is a basic feature.

If there isn't clipboard, there's no point in using VS Code.

Dupe of #40

**Comment by lramos15** [comment]
Please go into more detail about what you're looking for. The hex editor already works with some clipboard features.

**Comment by jtagcat** [comment]
Have your cursor at a position, pressing Ctrl+V I'd expect the text to be pasted (in insert mode, replacing with length; though no-insert, appending should be available as well).

**Comment by lramos15** [comment]
Sorry if I'm still confused let's say your current hex is 
`42 42 42` which in UTF-8 is `B B B`
Are you saying if your clipboard has 
`43 43 43` or ` C C C` on it pasting that should work and replace the current contents?

**Comment by jtagcat** [comment]
Note that the clipboard has `CCC`, not `C C C` (and it might be `434343`, `43 43 43`, `43	43	43`).

There are 2 ways of doing this:
a) Where you last clicked (you can always undo): If you last selected a hex field, paste there; if you last selected a text field, paste there as text (optionally default to always hex, at the position selected on text).  
If the clipboard content is incompatible with hex (0..F, ex contains `U` in it), paste it at the same position as text.

Optional animation (switch to orange, then fade back to black/white, etc depending on theme) where the content was pasted (the text selection, or hex positions). This would make it a good UI.

b) Always prompt (not great and annoying)
> This is a great idea and it would be necessary to differentiate whether you're dumping actual binary/string or a hex string - the way http://hexed.it does it is good :)

**Comment by Wassini** [comment]
The clipboard is not working at all. If I try to paste anything, nothing happens. I have tried with a string and a single letter.

**Comment by lramos15** [comment]
@Wassini currently it's only supported copy and pasting within the editor. Are you trying to paste an external string?

**Comment by connor4312** [comment]
There are [improvements to make](https://github.com/microsoft/vscode-hexeditor/issues?q=is%3Aissue+is%3Aopen+paste) here, but we support pasting now

**Comment by Niigin00** [comment]
What I've noticed is that there is not option to paste numbers into the hex editor from outside of the hex editor, which makes it completely unusable for the purpose I wanted to use it for. Maybe that's what jtagcat meant.

**Comment by Niigin00** [comment]
Maybe what jtagcat meant is that there is no paste option on the menu you get when you right-click on something. You have to use CTRL-V, and there is nothing to tell you this. It does work even for pasting from outside of vscode-hexeditor, though.

**Comment by Orbling** [comment]
Confirmed that the paste stops at the first NUL character, can't tell if the buffer has more than that, but for a hex editor that's quite a show stopper.  I wanted to use the HEX Editor to find a section of a binary and copy it in to a new file, finding the section was ok ish, albeit somewhat painful selection, but can't paste in to a new buffer because of that issue.
