### ISSUE TITLE
UTF-8 Path support?

### ISSUE THREAD

**Issue by clzls** [microsoft/vscode-hexeditor#194]
When I tried to load some file with a path containing CJK characters, I got an error below:
`Unable to open 'data.c': Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range..`

I moved it to root, gave it a ASCII name and it worked. But my code are all named with CJK characters...

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/108431
