### ISSUE TITLE
扩展不可用

### ISSUE THREAD

**Issue by fengzhuo17** [microsoft/vscode-hexeditor#195]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

Issue Type: <b>Bug</b>

选择以其他方式打开，选择Hex Editor，然后显示报错。

无法打开“tttttt”: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

我回滚到1.1.0及更早版本时，可以打开。新版本打开均显示报错，目前最新1.3.0，报错信息如上所示。

Extension version: 1.3.0
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (4.26GB free)|
|Process Argv|C:\Users\冯卓\Desktop\test --crash-reporter-id 794e6ac0-eb23-4e40-b31e-29361b6ab71f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Duplicate of #194

Also please use English when filing issues in the future
