### ISSUE TITLE
Data inspector values are not updated during selection

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode-hexeditor#200]
Issue Type: <b>Bug</b>

Click on single byte correctly updates values in data inspector, however if I select few byte cells with mouse - values are not updated and may be not related to selected bytes at all.

See how data changes with click on single byte, but stuck if is select few bytes in bottom row.
https://user-images.githubusercontent.com/1312662/104371590-71216980-5528-11eb-9965-028a2e399457.mp4

Expected behavior:
Update inspector values when selection happens. Maybe just clear everything if it will be unclear from which byte value computation starts (start of selection vs end of selection).

Extension version: 1.3.0
VS Code version: Code - Insiders 1.53.0-insider (e17aea136d32fdb06d9b32184b04ccd36bb51e9c, 2021-01-12T08:23:24.929Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (16.33GB free)|
|Process Argv|--crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry914:30244316
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by lramos15** [comment]
Hmm. This is an interesting one, and I don't know what the best behavior is, if you have a large selection then a large part of your selection is useless to the data inspector is it does at most 64 bits or 8 bytes / cells. This means anything over 8 cells selected and we would be truncating the selection. I would assume it would be from selection start because program languages are predominantly read left to right, but then you have this disconnect as your cursor is at the end of the selection, and you are used to the data inspector calculating its information from the cursor location.

**Comment by IllusionMH** [comment]
My current expectation for this one is to either show from start of selection (leftmost/earliest position of selection in document, because you can perform selection from right to left) or remove all values from data inspector (at least whey won't be related to different part of file).

Ideal solution that I can imagine #174 - show all fields values if only 1 byte is selected (as it works now) and in case of selection that has more that one byte - only values corresponding to selection length. 2 bytes - `Int16`/`UInt16`, 4 bytes - `Int32`/`UInt32` and so one.

I've opened this one as issue because separately current behavior is confusing and decision to "clear all fields" is easier to implement than #174 which is nice to have improvement.

**Comment by lramos15** [comment]
@IllusionMH I think I came up with a decent compromise here, but let me know. I have the data inspector update `onMouseUp` so that you don't have it flashing as you do your selection. It then takes the first 8 bytes of your selection starting from the left.

**Comment by IllusionMH** [comment]
@lramos15 this approach works fine except case when you perform selection left-to-right: last cell will have cursor outline and this can be confusing.

Maybe removing data from inspector is not bad alternative. Or having "message" like "Selection start value" above fields so it will be clear that value is from selection start and not selection end.
