### ISSUE TITLE
Data inspector preview for multiple bytes

### ISSUE THREAD

**Issue by skyhirider** [microsoft/vscode-hexeditor#208]
Can the data inspector be extended to show the preview for more than one byte?

I selected multiple bytes but it still shows only the first selected instead of grouping them.

Something similar to this but directly in VS Code https://www.scadacore.com/tools/programming-calculators/online-hex-converter/

**Comment by lramos15** [comment]
It does preview multiple bytes. But it's not very clear what it's doing. Here is an example https://github.com/microsoft/vscode-hexeditor/issues/207#issuecomment-768325801

**Comment by lramos15** [comment]
If you're talking about like 8 bit showing multiple different bytes. I think that would make the panel feel very cramped.

**Comment by skyhirider** [comment]
True, but it would be nice to have. Or have a button that would show the inspector preview in another window.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-hexeditor/issues/174
