### ISSUE TITLE
Hex Editor Backlog

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-hexeditor#211]
This issue will outline the major features which are required to offer a basic set of complete features for the hex editor. These features currently do not have a timeline, but would greatly increase the use and polish of the extension.

- The hex editor should be accessible, supporting screen readers and keyboard only navigation #4 
- Responsive UI. I.e. font size changes, hex grouping changes, line spacing, etc. #6, #44, #210
- Editor should support insertion and deletion of cells #71 
- Support for binary templating to allow for large amounts of editor customization (this is a large request which would require many pieces see https://github.com/microsoft/vscode-hexeditor/issues/50#issuecomment-663935031) #50.

/cc @kieferrm

**Comment by connor4312** [comment]
Closing this out for housekeeping, we can track in individual issues
