### ISSUE TITLE
Search by Offset or Position

### ISSUE THREAD

**Issue by pnvnd** [microsoft/vscode-hexeditor#212]
Is there a way to search by offset or position?  For example, in Visual Studio Code, I can use `CTRL` + `G` to go to a specific line of code.  I'd like to be able to do something similar with the hex editor and go to a specific position like  `001830A8` and jump to this position highlighted.

**Comment by scsteel** [comment]
Hexeditor already has a command to move to a specified offset: hexEditor.goToOffset, which is accessible from the command palette (menu View|Command Palette, or Ctrl+Shift+P).

However, you can make it work like you want by adding the following to your keybindings.json file, then will assign Ctrl+G to invoke this whenever your in a hexEditor window:
[
    {
        "key": "ctrl+g",
        "command": "hexEditor.goToOffset",
        "when": "activeCustomEditorId == hexEditor.hexedit"
    }
]

It would be great if the extension defined this keybinding (or equivalent) by default.

**Comment by pnvnd** [comment]
Excellent! This is now working as expected, thank you!
