### ISSUE TITLE
Page up and down should move the selection, not just scroll

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#22]

**Comment by tommai78101** [comment]
Just curious, wouldn't the Alt + Up / Down arrow be suffice to move the selection up/down?

I'm holding down ALT + Arrow keys to move the selection around in the Hex Editor view.

Or maybe this feature isn't really fleshed out for selection / cursor navigation, or that this feature is part of the editing features which were said to be the focus after all the viewing features are in.

**Comment by Tyriar** [comment]
I believe most hex editors use page up/down to move the selected cell a page up or down, just like in vscode's editor too.

**Comment by tommai78101** [comment]
Oh I see. I didn't know of this feature being a common feature among hex editing softwares.
