### ISSUE TITLE
I really don't like the data inspector side bar

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#223]
Reasons:

- It hides my explorer or whatever side bar I have displayed at the time, this is not only distracting but I like it to be there to give me context on where I am within the project
- There is _so much_ room for this on the right of the editor
- There is also a lot of wasted space on the bottom of the data inspector
- I can't seem to be able to bring it into my explorer which might be alright, provided I doesn't auto show the explorer when I focus the editor

![image](https://user-images.githubusercontent.com/2193314/111050074-90425780-8402-11eb-83fd-ed9e1403b451.png)

**Comment by lramos15** [comment]
As you remember, it was on the right side of the editor before and moved into the side panel to act as an information panel of sorts as it felt weird living next to editable content. I assume we could eventually add more stuff to the data panel, but I'm not sure what. We can discuss this at the UI/UX sync, but I'm not sure what a good place to put it is unless we throw it under a setting and let the user decide?

**Comment by Tyriar** [comment]
I never had an issue with it on the right side, I know others brought it up though. I'd prefer the editor to be more self contained and not mess with how I do things with the side bar.

**Comment by Tyriar** [comment]
After doing https://github.com/microsoft/vscode-hexeditor/pull/252 I figured out how to pull it into another one, I think I just didn't hold the mouse over an activity icon for long enough.
