### ISSUE TITLE
Switching endianness should be a single click 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#224]
It's a pain to change in a dropdown as it's 2 clicks, it would be better as a radio button style input.

<img width="224" alt="Screen Shot 2021-03-17 at 11 33 27 AM" src="https://user-images.githubusercontent.com/2193314/111519702-9a22ce00-8714-11eb-9c57-0a3aaecc4705.png">

<img width="220" alt="Screen Shot 2021-03-17 at 11 33 23 AM" src="https://user-images.githubusercontent.com/2193314/111519728-9ee78200-8714-11eb-82dc-3da22bef5a35.png">

**Comment by lukebrowell** [comment]
Or a toggle switch behaviour similar to the 'install'/'installed' ActionViewItem used for extensions perhaps @Tyriar?

![image](https://user-images.githubusercontent.com/1446740/129124755-dedf75e9-4b86-43a2-9366-8092de1b8a0a.png)

![image](https://user-images.githubusercontent.com/1446740/129124949-735abfca-b30f-47ca-8799-ab7aedf6053d.png)


References:
- [actionbar](https://github.com/microsoft/vscode/tree/900f30989d49bcc9356e2a224c9841da33cd1726/src/vs/base/browser/ui/actionbar)
- [actionViewItem](https://github.com/microsoft/vscode/blob/104bc571e956e4af623905ef10dfcc8f0fdac625/src/vs/workbench/contrib/extensions/browser/extensionsActions.ts#LC773)

**Comment by connor4312** [comment]
It's now a checkbox
