### ISSUE TITLE
"Hex Editor: Close hex editor" please add this command to the command palette 

### ISSUE THREAD

**Issue by jonasfrey** [microsoft/vscode-hexeditor#235]
how tf should i memorize the command "View: Reopen editor with...", please create the command "Hex Editor: Close hex editor" which closes the hex editor and switches back to the Built in Text editor.

Thanks

**Comment by Tyriar** [comment]
This should probably be a general discussion on custom editors in the vscode repo.

**Comment by lramos15** [comment]
@Tyriar This definitely is a common confusion.

@jonasfrey There is also `View: Toggle Editor Type` which will bring you back to the text editor if that is easier to remember

**Comment by lramos15** [comment]
Closing this as won't fix as there is `View: Toggle Editor Type` and `Reopen With...` if we want to introduce `Close ....` or whatever I think it should be something in core VS Code as that means the current two methods are not discoverable enough

**Comment by connor4312** [comment]
There's also the `View: Reopen with Text Editor` command if the user wanted a single-button/command swap
