### ISSUE TITLE
[QUESTION] How do you add HexEditor as an editor option

### ISSUE THREAD

**Issue by codinginpython123** [microsoft/vscode-hexeditor#237]

**Comment by Tyriar** [comment]
This is explained in the readme here: https://github.com/microsoft/vscode-hexeditor#how-to-use

**Comment by codinginpython123** [comment]
I meant as an extension it add its own custom editor. How do I do it in my VSCode extension

**Comment by Tyriar** [comment]
Oh ok, here's the docs for that: https://code.visualstudio.com/api/extension-guides/custom-editors

The hex editor and [the sample](https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample) are good references.
