### ISSUE TITLE
Open active file in hex editor doesn't work when another custom editor is opened

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#239]
Not sure if the repro is another custom editor or related to the file type.

Repro:

1. Install Luna Paint
2. Open an image
3. Run the open active file in hex editor command, it focuses the explorer

![recording (8)](https://user-images.githubusercontent.com/2193314/111466646-c886b600-86e0-11eb-9e70-8e532ae95b89.gif)

**Comment by Tyriar** [comment]
This is because `registerTextEditorCommand` is used, not `registerCommand`. The fix should be easy, but I don't know how to get the uri for the active _editor_ (not necessarily text).

**Comment by lramos15** [comment]
Yeah this is a long standing issue, VS Code currently doesn't have an API to get the URI for the active editor. It's heavily requested and I know @eamodio was working on it at one point but I don't know the current progress. This is a command I added for discoverability but it doesn't work from custom editor to custom editor. I guess we could surface a notification here, although I do like to avoid notifications :)

**Comment by Tyriar** [comment]
I see there's a propose `openEditors` API, maybe that would do it. Though I'm not sure we know which is the active one.

**Comment by LinqLover** [comment]
This one is probably caused by the same problem: When I open a binary file in VS Code, instead of a regular text editor, a message is shown stating that the file encoding is not supported. "Open active file in hex editor" does not work in this scenario, either.

**Comment by Tyriar** [comment]
@lramos15 I hit this again the other day, how about in the failure case we just run the reopen editor with command as a workaround? That's a lot nicer and more convenient than just nothing happening.

**Comment by lramos15** [comment]
@Tyriar this is still blocked until the finalization of https://github.com/microsoft/vscode/issues/133532 because we do not know the URI of the active tab and therefore cannot use the commands

**Comment by Tyriar** [comment]
@lramos15 it's active, so you can just run the ` workbench.action.reopenWithEditor` command.
