### ISSUE TITLE
The focus border is too subtle

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#24]
It's too difficult imo to tell the difference between selected unfocused:

![image](https://user-images.githubusercontent.com/2193314/84065736-b3267380-a979-11ea-97f7-14da7742d3e5.png)

And selected focused:

![image](https://user-images.githubusercontent.com/2193314/84065722-ae61bf80-a979-11ea-9f0f-598ba5a49e10.png)

The only difference is it looks slightly blurry.

**Comment by Tyriar** [comment]
You shouldn't just use the status bar bg for this as then theme authors will have problems with it - a lot of themes use a very muted status bar background. `focusBorder` is good, I think the problem is more with the background color applied to the focused cell. Consider all the states a cell can be in, you should be able to easily differentiate each of them, and not just by color is important for accessibility.

**Comment by lramos15** [comment]
I was trying to use VS Code colors to allow theme authors to still be able to theme everything / not have to maintain my own color palettes as extensions only get access to three "categories" of themes which is light, dark, and high contrast. I'll ask @misolori  his thoughts and what the best color scheme might be.

**Comment by Tyriar** [comment]
Perhaps borrowing from the list colors would be better?

**Comment by misolori** [comment]
I think you're running into the issue where we don't normally uses list colors and focus together, there are specific tokens for each one.

One alternative you could try is to fade out the text that isn't selected and use the list color styles, and then apply an offset on the outline so it stand out:

![image](https://user-images.githubusercontent.com/35271042/84447896-1f190e00-abfe-11ea-990b-1aca6c722cd3.png)

**Comment by lramos15** [comment]
I don't really like the grey text with light grey headers as I feel the contrast between the two is lost. I do really like the thicker outline with a little bit of offset as I believe that makes it look super clear what is focused.  
![image](https://user-images.githubusercontent.com/4544166/84513766-efb6df80-ac97-11ea-976c-d0b72f0fefd3.png)

Thoughts on this?

**Comment by misolori** [comment]
It's better, but it's really hard to focus on it because of the white text in the background. The decoded text part is easier to scan because of this. Another thing you can explore is making sure all of the number elements are evenly squared (makes it easier to scan). Right now it's wider and makes your eyes work a bit harder.

**Comment by Tyriar** [comment]
@misolori making them square would reduce the amount of rows that can fit on the page?

**Comment by misolori** [comment]
@Tyriar probably, but it's so much easier to read:

### Before
![image](https://user-images.githubusercontent.com/35271042/84524486-e7a67200-ac8e-11ea-9e52-c96b5af1bcc5.png)

### After
![image](https://user-images.githubusercontent.com/35271042/84524453-da898300-ac8e-11ea-9fde-bd14876e9953.png)

**Comment by Tyriar** [comment]
Personally I tend to not like reducing information density like this, it's cutting off ~1/3 of the content which could be important for the task at hand and end up increasing the amount of scrolling needed. Leveraging `editor.lineHeight` would be better imo as that's the user's preference.

**Comment by Tyriar** [comment]
Looks like the PR will only be square for certain font family/size combinations.

**Comment by lramos15** [comment]
I can look into `editor.lineheight` I'm not really sure what the best solution is here. I feel that the offset helps a lot and solves the underlying problem. The squaring is to supposed to help with readability and I'm not sure if it makes a huge difference as the ascii section cannot be square due to the use of spans.
