### ISSUE TITLE
Data inspector sometimes fills in data for 0 when opening a file

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#240]
Repro:

1. Open a file
2. The data inspector sometimes shows info for `0x00` even though nothing is focused?

<img width="1095" alt="Screen Shot 2021-03-17 at 5 24 24 AM" src="https://user-images.githubusercontent.com/2193314/111466873-0be12480-86e1-11eb-88bc-543b6ec41bdb.png">

**Comment by connor4312** [comment]
We don't show the data inspector if nothing is focused anymore
