### ISSUE TITLE
Focusing the editor will always force focus the data inspector

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#253]
@lramos15 I don't understand why forceFocus exists:

https://github.com/microsoft/vscode-hexeditor/blob/26518ca170eb806f403a66bc1ac563e4d8eab7df/src/dataInspectorView.ts#L63-L68

**Comment by lramos15** [comment]
I used it to force the data inspector to be the panel you see when you open a hex document. You can remove it if that happens anyways, I just figured it would help discoverability as you want the panel to be visible when you're using the editor.

**Comment by Tyriar** [comment]
Ah ok, yeah I think we just want to outright remove it now. Not the best experience currently as you focus a file and then press down and it scrolls the data inspector

**Comment by Tyriar** [comment]
Struggled figuring this one out, there is some code like above that forces focus, but even without that the webview panel seems to always take focus when it's displayed. It might be getting triggered when displayed by the core, @mjbvz could you verify whether that's expected?
