### ISSUE TITLE
Support custom data types in the data inspector

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#257]
Suggestion from https://twitter.com/soworston/status/1372563165427466240

Basic idea: Define a struct and their data types to easily view it. This would have been handy when I was implementing an .ico file parser recently by defining a struct for the [header and icon directory](https://en.wikipedia.org/wiki/ICO_(file_format)#Outline) to make it really easy to read the data out for multiple files.

I wouldn't expect this to be too difficult if there was an option to define the struct in the data inspector, it may need to request additional adjacent bytes from the main hex editor webview though.

How the struct is entered is a bit of an unknown (eg. all text vs input/select fields).

**Comment by Tyriar** [comment]
Related idea: Integrating the hex editor with `kaitai-struct` which are a convenient way to pull structs out of binary files

**Comment by lramos15** [comment]
Seems like a duplicate of https://github.com/microsoft/vscode-hexeditor/issues/50. Although smaller scope.

**Comment by Tyriar** [comment]
Yeah it's a duplicate 👍
