### ISSUE TITLE
Hex editor: cut off characters with larger font sizes

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-hexeditor#259]
Testing https://github.com/microsoft/vscode/issues/119206

hexeditor-1.5.0.zip, MacOS, 
VSCode 1.55.0-insider, Commit: a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e, Date: 2021-03-23T05:13:33.822Z

Set `"editor.fontSize": 25`
Select some content in the hex editor
![image](https://user-images.githubusercontent.com/6461412/112177594-5e4aa580-8bf9-11eb-976a-6e9da6beaf27.png)

Even bigger:
![image](https://user-images.githubusercontent.com/6461412/112177880-994cd900-8bf9-11eb-92f5-3e3823163951.png)

**Comment by lramos15** [comment]
https://github.com/microsoft/vscode-hexeditor/commit/de1b285fa54c28bbd0ddafc82d318926fe135f4a
