### ISSUE TITLE
Hex editor: Find/replace widget needs a border

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-hexeditor#260]
Testing https://github.com/microsoft/vscode/issues/119206

hexeditor-1.5.0.zip, MacOS, 
VSCode 1.55.0-insider, Commit: a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e, Date: 2021-03-23T05:13:33.822Z

- open a file in the hex editor
- open the Find widget (Cmd + F)

![image](https://user-images.githubusercontent.com/6461412/112179837-50961f80-8bfb-11eb-9f9c-79a4335d4d15.png)

**Comment by lramos15** [comment]
https://github.com/microsoft/vscode-hexeditor/commit/396e6354751d8e84bc7b97c638ddeac8d0f7c7bb
