### ISSUE TITLE
Hex editor: Can't close the find widget

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-hexeditor#261]
Testing https://github.com/microsoft/vscode/issues/119206

hexeditor-1.5.0.zip, MacOS, 
VSCode 1.55.0-insider, Commit: a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e, Date: 2021-03-23T05:13:33.822Z

- open a file in the hex editor
- open the Find widget (Cmd + F)
- I don't see how to close the find widget

![image](https://user-images.githubusercontent.com/6461412/112179837-50961f80-8bfb-11eb-9f9c-79a4335d4d15.png)

**Comment by lramos15** [comment]
Right now the only way to close it is through escape, but I agree an X button should be added to feel more similar to VS Code.

**Comment by lramos15** [comment]
Fixed https://github.com/microsoft/vscode-hexeditor/commit/396e6354751d8e84bc7b97c638ddeac8d0f7c7bb
