### ISSUE TITLE
Data inspector is empty on Web

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-hexeditor#262]
Testing https://github.com/microsoft/vscode/issues/119206 
![image](https://user-images.githubusercontent.com/876920/112188577-54f11700-8bc0-11eb-9803-258c3eaddcc5.png)

* Install Hex Editor on codespace
* Open a file
* Data inspector is empty

**Comment by lramos15** [comment]
<img width="1130" alt="Screen Shot 2021-03-23 at 2 09 12 PM" src="https://user-images.githubusercontent.com/4544166/112196450-6eef2180-8be1-11eb-89f4-1a37d26c25bf.png">

Hmmm, was there anything in developer tools. Mines not empty on edge in a codespace

**Comment by rebornix** [comment]
When I'm testing on macOS/Edge/Codespace, the webview in the sidebar doesn't finish loading.

**Comment by lramos15** [comment]
Hmm. That's my exact setup as well and I don't see any issues. I also saw in your video for the overlapping decoded text it was loaded?

**Comment by lramos15** [comment]
Can't repro so closing for now. Feel free to re-open if it's still an issue.
