### ISSUE TITLE
Cmd+F opens both find widget and browser find

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-hexeditor#263]
Testing https://github.com/microsoft/vscode/issues/119206

![image](https://user-images.githubusercontent.com/876920/112188845-9b467600-8bc0-11eb-843c-53838015ec8f.png)

In Monaco Editor, cmd+f will only open its inhouse find widget.

**Comment by lramos15** [comment]
https://github.com/microsoft/vscode-hexeditor/commit/31c2df8d692941d0f427dbf27928fcfa12085c54
