### ISSUE TITLE
Shift+arrow does not support selection shrinking

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-hexeditor#265]
Testing https://github.com/microsoft/vscode/issues/119206

* Select a cell
* Shift+rightArrow to expand the selection
* Shift+leftArrow should shrink the selection but it doesn't now

**Comment by connor4312** [comment]
This does now (or did) but it's buggy :(

**Comment by connor4312** [comment]
Dead simple fix, we just used the wrong method 🤦
