### ISSUE TITLE
Home/end behavior

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#27]
I notice https://hexed.it/ uses home and end to go to the start and end of the document respectively, is this standard across all hex editors? It would be better if we aligned with the editor imo and have home/end go to the start/end of the _line_ and ctrl/cmd+home/end go to the start/end of the file.

**Comment by lramos15** [comment]
I agree we should try to make the hex editor feel like the editor in VS Code since it should just feel like another editing experience inside VS Code. I have added this functionality in the scrollbar branch will get pushed with the next release

**Comment by lramos15** [comment]
Fixed in #39
