### ISSUE TITLE
Cmd+right after cmd+left loses selection start

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-hexeditor#271]
Testing https://github.com/microsoft/vscode/issues/119206

* In monaco editor, with text `abcdef`
  * Put cursor after `c`
  * cmd+shift+arrowLeft will select `abc`
  * cmd+shift+arrowRight will then select `def`
* In hex editor
  * Put cursor in the middle of a line
  * cmd+shift+arrowLeft will select from the cursor to the line start
  * cmd+shift+arrowRight selects the whole line

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode-hexeditor/issues/128
