### ISSUE TITLE
Left overs in decoded text

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-hexeditor#274]
Testing https://github.com/microsoft/vscode/issues/119206

https://user-images.githubusercontent.com/876920/112196150-fc257c80-8bc7-11eb-9265-e09cb779b3ba.mov

As shown from above recording, it seems there are some left overs in the canvas. When I click on hex `72`, it's rendered as `r` on the right side, but when I move the focus to another cell, the decoded text is somewhat different.

**Comment by lramos15** [comment]
This looks like a bad rendering bug. As you see all the rows are overalpping one another. I'll play around with the CSS and try to find a better fix, do you only see this on web?

**Comment by rebornix** [comment]
I'm seeing this on Web and my font size is set to 20

**Comment by connor4312** [comment]
Seems to be fixed with the revamp
