### ISSUE TITLE
Data inspector broken on Remote SSH Window

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-hexeditor#275]
Testing https://github.com/microsoft/vscode/issues/119206

hexeditor-1.5.0.zip, MacOS, 
VSCode 1.55.0-insider, Commit: a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e, Date: 2021-03-23T05:13:33.822Z

![image](https://user-images.githubusercontent.com/6461412/112210699-4dab2700-8c1b-11eb-8c2d-acc96bfc9808.png)

**Comment by Jed-Z** [comment]
Same issue with 1.5.0, on VS Code 1.55.2 for Windows. 

Btw, it can be fixed temporarily by reopening the data inspector (by clicking the hexagon button in the left side bar twice). But everytime I switch to another file and switch back the problem shows up again.

![Snipaste_2021-04-20_18-50-25](https://user-images.githubusercontent.com/32293986/115384208-5a666f00-a209-11eb-8524-f8a6b37ba3ca.png)

**Comment by connor4312** [comment]
Seems fixed with the editor rework
