### ISSUE TITLE
Copy/Paste does not work across hex editors

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-hexeditor#277]
Testing microsoft/vscode#119206

hexeditor-1.5.0.zip, MacOS,
VSCode 1.55.0-insider, Commit: a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e, Date: 2021-03-23T05:13:33.822Z

- Open two hex editors side by side
- Copy a character in the first hex editor and try to paste it in the second. 
- Paste does not do anything

**Comment by lramos15** [comment]
Seems to work for me, so closing. If you see it again let me know
