### ISSUE TITLE
Find widget disappears when switching editors

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-hexeditor#278]
Testing microsoft/vscode#119206

hexeditor-1.5.0.zip, MacOS,
VSCode 1.55.0-insider, Commit: a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e, Date: 2021-03-23T05:13:33.822Z

- open a file in the hex editor
- open the find widget
- switch to another editor (hex editor becomes hidden)
- bring the hex editor to the front. Find widget is gone

**Comment by irvnriir** [comment]
For me the find widget doesn't open at all .

**Comment by lramos15** [comment]
@irvniir ctrl/cmd + f should open the find widget for you.

**Comment by lramos15** [comment]
@aeschli Would the expected behavior here be that the find widget persists and recalculates search upon switching files similar to the monaco editor? That can be quite expensive, or would you expect it to just be a state specific to the document.

**Comment by aeschli** [comment]
@lramos15 Yes that's what the find/replace widget in the text editor seems to do.
There they have have this `?` instead of a full count , I believe it's related to performance too. 
@alexdima Can you give some insights?

**Comment by irvnriir** [comment]
@lramos15 ty . i was using GUI item that calls `vscode.commands.executeCommand('actions.find');` .

**Comment by alexdima** [comment]
> There they have have this `?` instead of a full count , I believe it's related to performance too. 

Regarding perf limits, the editor find widget has a limit of 20k results:
![image](https://user-images.githubusercontent.com/5047891/112948134-f84da900-9137-11eb-8956-1af0d35d3e9e.png)

`?` is rendered in some conditions at `? of X` when the selection is not intersecting a find result.

**Comment by connor4312** [comment]
This is a duplicate, and is fixed with some of the React work.
