### ISSUE TITLE
Feature request: Support for .tbl files

### ISSUE THREAD

**Issue by livvy94** [microsoft/vscode-hexeditor#290]
Some types of reverse-engineering such as ROM hacking make use of something called table files, and certain hex editors support loading them. Some examples are [here](https://datacrystal.romhacking.net/wiki/Category:TBL_Files). In these examples, text is stored based on the letters' locations in graphics memory, which means that UTF-8 or other otherwise common encodings are unheard of. 

![image](https://user-images.githubusercontent.com/12562322/118362906-c796c700-b55f-11eb-98b4-31983d8b8097.png)
`A` is 0xC1, `B` is 0xC2, etc.

Other features of the .tbl file include DTE (dual-text encoding), which is when multiple letters are squeezed into one location in graphics memory. For example, in the NES game EarthBound Beginnings (pictured above), 0x83 is `'s`.

Game-specific control codes are supported as well. For example, 0x01 is `<newline>`, 0x02 is `<pause then overwrite>`, 0x03 is `<pause for A press>`, and 0x00 is `<end>`. In the editor pictured below, I use the tab key to switch focus to the hex side, type the hex number, and then tab back to the text view.

![image](https://user-images.githubusercontent.com/12562322/118362815-3de6f980-b55f-11eb-8794-386ec2dd6b19.png)
I mainly use this legacy hex editor to do this kind of work, but it would be extremely convenient if VS Code could have this functionality.

**Comment by lukebrowell** [comment]
I can certainly see how useful this would be for optimised character encodings used in resource-constrained applications, eg Game Roms, ScummVM, embedded IOT devices etc.

From my brief reading, I understand that a Text Table or .TBL file provides a flat lookup, which enables a developer to work with reduced-size character encodings by representing whatever the corresponding strings are in the editor.

Each line is in the table file is a lookup between the binary data (hexadecimal form) and the corresponding string in the particular character encoding. 

Example:
```tbl
01=a
02=b
03=c
```

Blank lines in the table lookup file are ignored.

To indicate a newline character we use *HEX
```tbl
*03
```

'Bookmark' lines are done like this:
```tbl
(01h)Title 
```
Where the **_h_** after the hexadecimal address inside the brackets tells the editor that can read table files that the characters preceding it are to be read as a hexadecimal. 

@vince94 Couple of questions:
- Are you already planning to raise a PR for this yourself?
- Can you recommend a good open-source hex viewer that we could reference the implementation of for what you're proposing?
- How would you want the table file(s) to be referenced so as to be used for looking up a block of hex within a file? 
- Would you envisage it being read-only, or read/write?
- What about more sophisticated data encodings like protobuf?

**Comment by vince94** [comment]
Hello! I just saw this, sorry it's taken me so long to respond. I'm not familiar with this project's codebase, so I don't plan on making changes and doing a pull request myself. WindHex is the only hex editor I know of that implements this feature in such a useful way, but unfortunately, it was never made open-source. If you're interested, you can download it [here](https://www.romhacking.net/utilities/291/). 
The way it references the table file is that you open the binary file, ROM, etc. in question, and it appears as the raw hex. Then you open a table file (with another Open File Dialog), and then the whole file is displayed based on the contents of the table file. If the table file's filename is identical to the binary file, then it is displayed automatically. 
I would envision it being read/write, as the use case is typing things in and having it automatically translated to the appropriate hex numbers. 
I've never heard of protobuf before, but it sounds fascinating! I'm going to need to do more research on it, I'm curious if that kind of data serialization has any applications in ROM hacking.

**Comment by pnvnd** [comment]
I'd also like this feature implemented, as I am also stuck using WindHex32.  Here's a video of how I would normally like to use the hex editor with TBL file support: https://www.youtube.com/watch?v=sYqcyVNRrjQ (first 2 minutes).

**Comment by connor4312** [comment]
Duplicates (would best be done with) https://github.com/microsoft/vscode-hexeditor/issues/50

**Comment by ketsuban** [comment]
I'm not sure #50 is the right tool for this job. Binary templates are fine for custom representations of selected chunks of data beyond "{un}signed 2ⁿ-bit integer", but a binary template for a custom encoding requires you to know where the text *is* to find out what it says; a table file solves the slightly different problem of "I know there's text in this file somewhere, but I can't just search for it because it's in an arbitrary non-ASCII-compatible format".

**Comment by lukebrowell** [comment]
Agreed Thomas it is a distinct feature, However I suspect that the admin may not have time/inclination to dig deeper while no PRs are forthcoming from the community.
