### ISSUE TITLE
Feature Request: Annotating Hex Files

### ISSUE THREAD

**Issue by dipsylala** [microsoft/vscode-hexeditor#291]
When I'm reverse-engineering I'll often view a file in Hex and manually annotate its structure. HexEditor is great for viewing these files, and the data inspector is excellent.

Using a WAV file as an example, I'd annotate the first 4 bytes with "RIFF Chunk Descriptor", the next 4 bytes with "Chunk Size", the next 4 with "Format" and so on.

Being able to apply annotations within the editor would greatly facilitate a bookmark-like structure, and being able to apply it to other files of the same type would be beneficial. This allows the user to quickly understand and jump to particular areas of the hex structure.

* A basic option could include a structure based purely on the offset. 
* A stretch goal could be to allow annotation length to be generated based on the contents of particular areas of the file. For example, a 'data' annotation area could be based on the contents of the 'data length' area of a hex file.

A _suggested_ UI approach would be through color coding the annotated areas, and have a mouseover tooltip, and showing the annotation in the Data Inspector area. In the Data Inspector area, the CRUD of annotations could take place, with creation based on what is currently selected. Annotations could act as bookmarks so that clicking on an annotation would select the appropriate bytes in the file.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-hexeditor/issues/68

**Comment by ipg0** [comment]
> @ipg0 I tried it and it conflicts with the default Hex Editor now / Yours doesn't allow resizing (caps at 0F) horizontally. I wish it could be rebased. The default one from microsoft is ass and I loved the coloring/tags

@Elyx0 
Unfortunately, my fork is currently way behind the Microsoft version, since I made it a long time ago when I needed it and haven't really been maintaining it since.

I'll see if I have time to rebase or even reimplement it in a proper way to open a PR over the next week, I'll keep you posted.
