### ISSUE TITLE
render error when trigger large file warning

### ISSUE THREAD

**Issue by ctuu** [microsoft/vscode-hexeditor#293]
![hex-test](https://user-images.githubusercontent.com/22322656/120882717-29e96180-c60c-11eb-8f2c-dea2c60fa927.gif)

vscode 1.56.2
windows 10 21H2 x64
hex editor 1.6.0 ~ 1.7.0

**Comment by lramos15** [comment]
Is this just a normal folder?

**Comment by ctuu** [comment]
> Is this just a normal folder?

yes, I just create the folder at desktop
