### ISSUE TITLE
Paste not working?

### ISSUE THREAD

**Issue by Wassini** [microsoft/vscode-hexeditor#295]
I have some texts in the copy buffer that I would like to view in hex for cheking the LF/CRLF/CR format.
Creating a new hex file and CTRL-V does nothing. Nor does the menu "paste".
How to I paste this into the hex viewer so I can see if it contains 0D0A or just 0A for linebreak?

**Comment by lramos15** [comment]
Can you record a gif of what you're seeing so. I can better understand please

**Comment by lramos15** [comment]
No info provided for over 60 days. Closing will reopen if more info is provided
