### ISSUE TITLE
Delete + Backspace is not working

### ISSUE THREAD

**Issue by Wassini** [microsoft/vscode-hexeditor#296]
Create a new file 
Open this (empty) file in hex view
Add a keystroke (letter) in the "Decoded text"
It is not possible to delete this again. (DEL, BACKSPACE, Ctrl-X, flame-thrower)

**Comment by lramos15** [comment]
The hex editor currently does not support deleting. You can do ctrl + z to undo your last edit but deletion is not currently supported.

**Comment by luxueyan** [comment]
Support deleting pls!

**Comment by lramos15** [comment]
@luxueyan This is something we want to do but is a lot more complex than the feature makes it seem
