### ISSUE TITLE
Feature request: Insert hex values

### ISSUE THREAD

**Issue by CassieXx0215** [microsoft/vscode-hexeditor#297]
I didn't find documentation about this, and I haven't figured out a way to do so, so I assumed it's not supported (yet).
Currently, we can only edit existing hex values. Sometimes we also need to add some extra bits, e.g. the scenario I am facing is that I am adding a file signature at the beginning of the file.

**Comment by rdautel** [comment]
+1 for this request. Working in the embedded space I often need to create hex files from scratch or add to/ delete from what I have.

**Comment by ggjulio** [comment]
Adding and removing some bytes would be great.
