### ISSUE TITLE
Big files don't even try to open?

### ISSUE THREAD

**Issue by TimeMaster18** [microsoft/vscode-hexeditor#298]
I tried opening a "big" file but had no luck at all, it warns about not being able to show properly but it doesn't look like it even tries:

![image](https://user-images.githubusercontent.com/50962671/123290194-5d375600-d511-11eb-92a7-67cacc1ff899.png)

Tried with files of 300MB and 40MB, same results.

**Comment by lramos15** [comment]
Duplicate #293
