### ISSUE TITLE
Feature Request: Default to big endian or save endianness choice

### ISSUE THREAD

**Issue by stravant** [microsoft/vscode-hexeditor#299]
Currently the value inspector pane defaults to little endian. This makes things frustrating / almost unusable when trying to inspect data which is big endian.

I see two obvious solutions to this:

* Save and use the previous choice of big / little endian when revealing the pane.

* Add a settings value for whether to default to little or big endian.

**Comment by lramos15** [comment]
We don't save the inspector value but we do have `hexeditor.defaultEndianness` as a setting
