### ISSUE TITLE
Horizontal scroll bar is opaque

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#30]
![image](https://user-images.githubusercontent.com/2193314/84076324-639c7380-a98a-11ea-8ea0-226a3a3b6d44.png)

Expectation:

![image](https://user-images.githubusercontent.com/2193314/84076384-7e6ee800-a98a-11ea-9a8e-932e780b5d4b.png)

**Comment by lramos15** [comment]
I believe this is because the hex editor uses a native horizontal scrollbar where the scrollbar for the editor is custom. The hex editor's custom vertical scrollbar is not opaque, but the horizontal one is despite using the exact same style rules.

**Comment by lramos15** [comment]
Closing because transparent native scrollbars aren't supported in webviews.
