### ISSUE TITLE
Hex editor: automated opening of hex view needs revisit

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-hexeditor#300]
The fact that clicking on a file that opens in hex editor automatically opens the hex view imho needs a revisit. Because when I click on something in the explorer I may want to modify the file from the explorer (e.g. copy / paste). But as soon as I click the explorer is gone.

**Comment by haneefdm** [comment]
I preferred the old WebView when the data inspector was part of the editor and not in the Side panel. My $0.02.

Before I could have two editors side by side be able to view data inspectors for both. I was having some other useability issues as well with the side panel as I was editing files of various types. 99% of the time I want either the File Explorer or the Debugger, it causes me to switch panels more frequently.

This should probably be a separate Issue/Enhancement request but, wanted to start here as it is a tiny bit relevant.

**Comment by haneefdm** [comment]
I am shelving my plan to integrate this extension into my debugger. The data inspector is causing a lot of usability issues while I am debugging and it is very difficult to use the hex editor while also debugging. Also, an issue when I have multiple hex editors open, I get only one inspector. Very unfortunate.

When I first used this, the data inspector was part of the Webview/editor which I really liked.

**Comment by lramos15** [comment]
New update just released! You can now configure where the data inspector is whether it's in the webview, shows on hover, or is in the sidebar
