### ISSUE TITLE
File watcher does not work if the URI is more than just a file-path

### ISSUE THREAD

**Issue by haneefdm** [microsoft/vscode-hexeditor#301]
I invoke this hex-editor from my debugger to examine memory. I use the baseAddress as part of the query string of the URI when I launch an editor. However when the contents of the memory changes, the file on disk gets updated with new contents.

While there is a file watcher, it does not work because the URI is more than just a file-path. It is because of this [line at](https://github.com/microsoft/vscode-hexeditor/blob/df3e5062e56fbcda3522f32957a2b835973e59bc/src/hexEditorProvider.ts#L71)

```TypeScript
			if (e.toString() === uri.toString()) {
```
I changed it to

```TypeScript
			if (e.fsPath === uri.fsPath) {
```
and things work as expected. If you wish, I can submit a PR. I wasn't sure if the fsPath's are canonical and if we have to a case-insensitive comparison on Windows. Seems to work, but wanted to ask.

Please advise.

PS: I was the one who added the baseAddress feature a while ago with your help

**Comment by lramos15** [comment]
This makes sense to me thanks @haneefdm I have pushed it. The filewatcher was listening based on `fspath` anyways so I'm not sure why I went with URIs. Case sensitivity also isn't an issue since they should match exactly due to the them coming from the same filesystem.
