### ISSUE TITLE
Feature Request: Support for read-only mode

### ISSUE THREAD

**Issue by haneefdm** [microsoft/vscode-hexeditor#302]
Perhaps there is already a way but is it possible to support read-only mode for the editor (becomes a viewer).

I was hoping to have this feature because I am showing hex files (frequently updated) for transient data which is a memory dump from a running program. I don't want users to modify the data. There is not a good way for my debugger to accept such changes and the side effects they might cause.

I can work on this if this feature is acceptable. I can pass the read-only mode as a query string like I am doing for `baseAddress` but if there is a better way, please let me know?

Thoughts and permission?

**Comment by lramos15** [comment]
Query parameters are a bit weird here. There is an idea of a readonly file system in vs code https://github.com/microsoft/vscode/blob/55868691efbc657fff97af72732e4d8482e11450/src/vs/vscode.d.ts#L7369-L7369

**Comment by haneefdm** [comment]
It is a bit involved but I could implement a file system. But that does not solve the UI issue that we allow edits to happen to a file that we have no way of truly saving. Sure they can save to disk but that doesn't actually do anything to the running program.

I tried changing the permissions of a file to read-only and it would still allow edits. I think that is the VSCode policy. So, a read-only file system would also do the same

Also not sure what happens to `File->Save As...`

**Comment by haneefdm** [comment]
I did not see anything in the `vscode.FileSystemProvider` that said it is a read-only file system. The only way to find out is to `stat()` a file/dir or get an error when a `writeFile()` is attempted. Sorry if I missed it.

Regardless, the extension needs to be modified if it detects that the file is read-only and disallows edits. But, AFAIK VSCode does not have a concept of a read-only file. You only find out when you try to save your changes.

https://github.com/microsoft/vscode/issues/99322

I actually agree with the VSCode policy.

This is why I was suggesting a `readOnlyMode` (I am bad with names) query string where the Hex-Editor becomes a Hex-Viewer.

**Comment by lramos15** [comment]
For filesystem we have 
https://github.com/microsoft/vscode/blob/55868691efbc657fff97af72732e4d8482e11450/src/vs/vscode.d.ts#L7369-L7369

For a specific file we must wait for
https://github.com/microsoft/vscode/issues/4873

**Comment by haneefdm** [comment]
Thanks so much for those links. OMG, there are sooo many use cases and I agree with most of them.

Guess we wait for microsoft/vscode#4873. Doesn't seem to be converging to a solution though but lots of agreement on needing such a feature

**Comment by gjsjohnmurray** [comment]
See also https://github.com/microsoft/vscode/issues/4873#issuecomment-865884638 for a pointer to how a FileSystemProvider can now (if using proposed API) state individual files as readonly (or not).

**Comment by haneefdm** [comment]
Thank you all, I have to try out the FileSystemProvider. It has other benefits for my purpose.
