### ISSUE TITLE
error loading stylesheet on github.dev

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-hexeditor#304]
Layout fails on `github.dev`, with following errors in console:

![image](https://user-images.githubusercontent.com/1487073/129632359-091a26e7-d140-4148-b356-aa60e2ad5d8a.png)

Here's a "Hello World" text file opened on the desktop:

![image](https://user-images.githubusercontent.com/1487073/129632501-3323abed-124c-40eb-8bac-d2e5ffb1fbb2.png)

And same file on `github.dev`:

![image](https://user-images.githubusercontent.com/1487073/129632536-5ab0f49c-fa5b-4f1b-b798-19db7aeb4319.png)

**Comment by tanhakabir** [comment]
Looks related to: https://github.com/microsoft/vscode-dev/issues/206

**Comment by lramos15** [comment]
This is a known issue with all custom editors that employ a CSP. Draw.io and Luna Paint disable CSP in web for this reason but it's a bug in core which I'm waiting on a fix for
