### ISSUE TITLE
No current tags?

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode-hexeditor#305]
1.3.0 is the only tag in this repository, but there are newer versions (current one is 1.8.2). Can you please add the missing tags and from now on tag new versions, too?

Currently GitHub shows that there's exactly one release - 1.3.0 from 2020 : https://github.com/microsoft/vscode-hexeditor/releases

**Comment by lramos15** [comment]
It's a lot of work to keep up with the tags and the marketplace releases. Is there a specific reason the tags are important? The marketplace shows what date the release is and allows you to install and download older versions. The changelog is also well documented

**Comment by GitMensch** [comment]
> It's a lot of work to keep up with the tags and the marketplace releases.

I volunteer to create a script for the missing ones, if the Changelog (or formerly README) change is the last commit for the releases I can use a its blame to create it quite fast.
Obviously this is only reasonable if there's both an expecting execution of the script and push of the tags to the repo and if upcoming versions will be tagged.

When you consider publishing, for example by GitHub action or other CI instead of the current approach publishing would be as easy as tagging with a release number in the future (optional, but possibly another reason to "tag clean").

>Is there a specific reason the tags are important?

If one currently wants to compare changes between releases one has to do this by finding the matching commit hashes manually. It is much more easy to git bisect or diff with tags up-front, and also the GitHub UI works much better when the tags are available.

The "the tag is actually shown as release" instead of the current "the most current release is 0.3.0" on the project's main page is only a little additional usefulness.

**Comment by lramos15** [comment]
I would be happy to take a look at a script to populate the old tags. Additionally maybe a github action which publishes a new release with the changelog changes when I push an update to the changelog would be the way to go.

**Comment by lramos15** [comment]
We have started to publish tags for new releases. We do not create a GitHub release at this time and instead rely on the CHANGELOG.md. Hopefully this is at least a step in the right direction

**Comment by connor4312** [comment]
There is [an option](https://github.com/microsoft/vscode-js-debug/blob/91ffddb82c1f7ed051efcbd40c78d779639df507/.ci/publish.yml#L27-L28) in the pipeline YAML to create a Github release, if we wanted to.

**Comment by GitMensch** [comment]
> There is [an option](https://github.com/microsoft/vscode-js-debug/blob/91ffddb82c1f7ed051efcbd40c78d779639df507/.ci/publish.yml#L27-L28) in the pipeline YAML to create a Github release, if we wanted to.

@connor4312 that sounds quite useful, is that active now?

**Comment by connor4312** [comment]
Unfortunately at this particular moment it's broken due to some Azure Pipelines access issues... but we have been consistently tagging all releases for the last year, and will continue to do so. The advantage of the pipeline yaml is mostly that people can then download .vsix's of older versions from the Releases page, though users of VS Code can already use the `Extensions: Install Specific Version of Extension...` command.
