### ISSUE TITLE
Binary file should be opened in hex editor by default

### ISSUE THREAD

**Issue by vivi168** [microsoft/vscode-hexeditor#31]
When opening a binary file, it should open the hex editor by default

![image](https://user-images.githubusercontent.com/1566422/84323032-4fb56500-ab76-11ea-9ab0-e7314100bf16.png)

**Comment by lramos15** [comment]
I will look into this, but I believe that there is no way to do this currently as that isn't information exposed to the extension API. The extension can only open certain files by default based on file ending.

**Comment by mika76** [comment]
I'm not sure this is how they plan things going forward. Looking at https://code.visualstudio.com/updates/v1_46#_custom-binary-editors you will be able to install custom viewers/editors for binary files so a hex view might not be expected as default.

**Comment by lramos15** [comment]
@vivi168 I would recommend opening a feature request against VS Code and hoping it gets enough upvotes. I think the solution would be to not open in the hex editor by default but instead have the open anyway open the quick pick with all the custom editors.
