### ISSUE TITLE
Display number of bytes selected

### ISSUE THREAD

**Issue by nickform-ost** [microsoft/vscode-hexeditor#317]
This is a pure enhancement suggestion that I'm posting on the off-chance that it inspires someone. The idea would be to display somewhere in the data inspector the number of bytes currently selected in the main hex display. Hopefully this would be fairly cheap to implement and it would really come in handy for inspecting formats where strings are encoded as a length followed by that number of bytes.

Apologies that I'm not able to donate the time to submit this as a pull request instead but thanks for reading and for all of the work maintaining this very useful extension!

**Comment by MoralCode** [comment]
i believe I have a first pass at this feature implemented on a local clone of the repo. will see if i can publish it as a fork/PR soon

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode-hexeditor/issues/86

**Comment by nickform-ost** [comment]
Thank you so much @MoralCode and @connor4312.
