### ISSUE TITLE
How do you use this extension?

### ISSUE THREAD

**Issue by jkwill87** [microsoft/vscode-hexeditor#32]
I can't figure out how to open the hex view for a given file. There isn't a hex language mode, any hex-related options in the command palette, or any context menu options for viewing files as hex. Please consider adding usage information to the readme.

**Comment by kidonng** [comment]
`Command palatte > File: Reopen with...`

**Comment by unl1ght** [comment]
It would be super helpful if this were added to the readme, or given a context menu option / command palette entry that appears when searching for "hex".

**Comment by lramos15** [comment]
Thank you all for the feedback. I have published version 1.0.1 which updates the README and adds an explicit open using hex editor command. I hope this will help with discoverability!
