### ISSUE TITLE
Hitting 'enter' in the replace widget does not replace selected match

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-hexeditor#322]
Testing microsoft/vscode#138092

In the VS Code text editor find/replace widget, hitting enter while your cursor is in the replace widget causes the next match to be selected and replaced. The hex editor's find/replace widget does not seem to do this, instead enter just advances the selection to the next match (and since I completely rely on this behavior to ensure that find/replace is doing what I expect, I actually thought find/replace wasn't working for a few seconds)

https://user-images.githubusercontent.com/30305945/144109703-2a577065-a6d8-467b-a204-39a41683a52f.mp4

**Comment by connor4312** [comment]
huh, I never used/realized this behavior, thanks 🙂
