### ISSUE TITLE
Feature request: Change default decoded text encoding to ASCII

### ISSUE THREAD

**Issue by SonOfLilit** [microsoft/vscode-hexeditor#323]
The "decoded text" window is used mostly to make plaintext sections in binary files easy to spot.

By using (I think?) `latin1` as the encoding, it is much harder to distinguish at a glance between noise that includes happens to include a lot of characters that look like text (many values >127 happen to look like characters in `latin1`).

Many have asked already to add an option to switch encoding to e.g. `UTF8`, `Shift-JIS` or whatever they happen to need. My request is that the default be set not to `latin1` but to `ascii`, the encoding used by most hex editors and for good reason (with all non-printable characters displayed as dots, perhaps in a different color to distinguish from real dot characters).

**Comment by lramos15** [comment]
We currently just use `String.fromCharCode` which doesn't really have an encoding but instead returns the unicode character see https://unicode-table.com/en/. 

We considers 0-32, 127-161, 173-174, and 256+ as unprintable.

**Comment by SonOfLilit** [comment]
Will you accept a pull request that considers all >127 as unprintable?

**Comment by lramos15** [comment]
I reviewed the other allowed characters and I understand where you're coming from. I went ahead and pushed it so printable characters are in the range [32, 127). We still display the UTF-8 and UTF-16 representations in the data inspector.
