### ISSUE TITLE
Feature request: Setting the amount of data per line and much more... :)

### ISSUE THREAD

**Issue by GSoftwareDevelopment** [microsoft/vscode-hexeditor#324]
I have some ideas to extend the capabilities of this tool.

1. I propose to add setting the amount of displayed data per line, as an option in plugin's inspection panel (Bytes per line)
2. Possibility to disable ASCII preview (hide ASCII preview)
3. Setting font for workspace
4. Possibility to set separate font for ASCII preview.
5. Maybe implement a tagging function (similar to the "Hex Editor with Tags" plugin or better :D )

It would be a (seriously) nice editor for retro coders :)

**Comment by lramos15** [comment]
1 and 2 should be all set!

**Comment by lramos15** [comment]
They're still being looked into. Number 5 is a huge ask that has many upvotes from others as well see https://github.com/microsoft/vscode-hexeditor/issues/50. It's just difficult to do

**Comment by GSoftwareDevelopment** [comment]
Yes, I understand perfectly the point. I just wanted to know your opinion on the rest of the points made :)
The #50 presented is a brilliant addition and I think it can easily replace my point 5. To quote myself: "similar to the "Hex Editor with Tags" plugin **or better** :D"

I'm following the development of the add-on and look forward to future updates.
I keep my fingers crossed and best regards.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-hexeditor/issues/175 and the other mentioned issues should cover this -- 1 and 2 are done. Closing this for housekeeping 🧹
