### ISSUE TITLE
Edit and Writing Feature Requestment(Strongly)

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-hexeditor#33]
Dear M$:
I am Embedded developer, and we often need to edit hex/bin files, and I've been looking for a plug-in that can edit these files in VSCode, because VSCode is my favorite code development tool. Now I've finally got a hexEditor, so we are **STRONGLY** recommend that writing-operations.
THANKS very much!

**Comment by lramos15** [comment]
Adding the ability to modify files is next up on the TODO list after finishing up a bit of UX polish. Hopefully initial editing abilities will come with the next release. See #17
