### ISSUE TITLE
Copy, cut and paste don't work in latest version

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#333]
Ext v1.9.3

This is a regression, it works in 1.8.2

![Recording 2022-01-25 at 05 30 40](https://user-images.githubusercontent.com/2193314/151005976-2fd206a9-c6bd-48b6-a2cf-b608526fb079.gif)

**Comment by sploitsmith** [comment]
Also having copy/paste issues today. Is it a related bug that when I select some bytes, then right click, the selection gets deselected? Or should I open a new bug?

**Comment by lramos15** [comment]
@sploitsmith It's fine to leave it as part of this bug. In the meantime if you're blocked feel free to right click the hex editor extension and select `Install another version...` this will let you install the previous version until a bug fix is released

**Comment by connor4312** [comment]
Working on this

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-hexeditor/pull/334
