### ISSUE TITLE
Signed int24 seems not working correctly

### ISSUE THREAD

**Issue by kresle** [microsoft/vscode-hexeditor#339]
For example, using little endian, 0x08F0FF is shown to be 117440512, which is way beyond 2^23, and the sign is incorrect.
(The correct number should be -4088)

**Comment by lramos15** [comment]
@paamand Do you want to try to take a look at this since you did the int 24 revision before? Seems to be giving incorrect values

**Comment by paamand** [comment]
Yes, sure.
But honestly I'm not sure how the test/deploy pipelines of VSCode
extensions work. Can I add a unit test or somehow modify the plugin
locally/point to a branch?
A link to how this is properly done would be helpful. Otherwise I can
suggest a untested fix.

//Paamand

**Comment by lramos15** [comment]
@paamand You should be able to debug it within vscode using the built in debugger. Just click `F5`. We have tests here https://github.com/microsoft/vscode-hexeditor/tree/main/src/test but they're more of the backend models. Let me know if you need any pointers

**Comment by lramos15** [comment]
This appears to be fixed in the currently published version
