### ISSUE TITLE
Add menu entry to open/edit file in HexView

### ISSUE THREAD

**Issue by EmbeddedBacon** [microsoft/vscode-hexeditor#34]
Hello,
  Please add a menu entry to an Editor Tab and in the Explorer view to open a file in the HexEditor.  I had to visit the issues tracker to actually figure our how to open a file in the HexEditor view.  

Thanks

**Comment by lramos15** [comment]
Thank you for the feedback. I have published version 1.0.1 which updates the README and adds an explicit open using hex editor command. I hope this will help with discoverability!

**Comment by EmbeddedBacon** [comment]
@lramos15, I don't understand why this issue was closed simply by adding a statement how to start the HexView.  This issue was to add menu items to two places, the Editor Tab and in the Explorer View (right click action on a file).   To simply dismiss this issue by adding a note in the read me file.  If you want wide adoption to use this useful tool you need to aid in its usage.  If I have to type out a long command sequence, in my opinion this how it works now, just to inact the view.

**Comment by lramos15** [comment]
Hi @EmbeddedBacon. You can right click a file in the explorer view and hit open with. I also added an explicit command to the command palette which is where most the editor commands live. This should mean you just have to open the command palette and type hex to be able to access the hex editor. For common files which you view as hex you can also have them opened by default in the hex editor by following the instructions in the readme and adding those file associations to your settings.json. After these changes if it still feels difficult to access the editor I would be open to further avenues to improve ease of use / discoverability.

**Comment by EmbeddedBacon** [comment]
@lramos15, thanks for the follow-up.  Okay, the "Open With" within the Explorer View is just fine.  Still would like to see an action item when right clicking on an Editor Tab.   Still, good start
