### ISSUE TITLE
New data inspector improvements

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-hexeditor#340]
I believe I may have been premature in merging the new data inspector as I forgot to actually test it and instead just was doing code review 🤦 . Just placing my findings here.

1. The sidebar data inspector inputs are no longer touching creating a divided look
2. UTF-8 and UTF-16 don't change with endianness changes
3. I understand the hover resizing but I don't know how I feel about the right side resizing.

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-hexeditor/commit/5d9c37c515917b4403c58fa04e3d48caa1aeed87
