### ISSUE TITLE
Values are rendered incorrectly at multiples of 0x3FFF0

### ISSUE THREAD

**Issue by tkuraku** [microsoft/vscode-hexeditor#346]
At multiples of 0x3FFF0 the values in a binary file are rendered as all zeros. This is a pretty serious bug. It caused me and colleague  to spend extra time trying to debug a hardware issue and  were misled looking for zeros when in fact there were none.  In fact if  you search for all zeros it will not find it, because internally it must know there aren't any zeros. Similarly if you copy that section it isn't zeros.  We found repeatable location of 0x3FFF0, but there could be other rendering bugs that we haven't found.

OS: Windows 10/ RHEL 8
versions: latest stable

![Screenshot from 2022-03-07 17-26-52](https://user-images.githubusercontent.com/11217294/157148105-f856713f-169b-4fd5-9caa-ffb2eb738122.png)

**Comment by tkuraku** [comment]
Any idea when this might be addressed? This extension is fantastic, but it is a little nerve wracking that you can't trust the displayed values.

**Comment by lramos15** [comment]
@tkuraku Can you provide a minimal file which reproduces this bug so that we can more easily investigate a fix 👍

**Comment by connor4312** [comment]
I can reproduce, will make a fix
