### ISSUE TITLE
Can't edit in VS Code

### ISSUE THREAD

**Issue by xiaowu2001** [microsoft/vscode-hexeditor#348]
I open a mp4 file in VS Code, using Hex Editor to open. But I can't edit it when I want to delete characters in VS Code.

**Comment by xiaowu2001** [comment]
I want to remove "FF", how to achieve it?
![image](https://user-images.githubusercontent.com/98504541/159849266-43a8ea29-52c2-4b79-b992-5726737bf41b.png)

**Comment by lramos15** [comment]
We currently don't support insertion or deletion just modification. See https://github.com/microsoft/vscode-hexeditor/issues/71
