### ISSUE TITLE
Data Inspector font appears to be fuzzy

### ISSUE THREAD

**Issue by EmbeddedBacon** [microsoft/vscode-hexeditor#35]
In the Data Inspector the fonts appear to be fuzzy and makes it hard to read

![image](https://user-images.githubusercontent.com/42427056/84342558-b3ca3000-ab5a-11ea-8076-4760c4de6946.png)

**Comment by nerdkid93** [comment]
I can reproduce on Ubuntu 20.04 LTS with VSCode 1.46.0 with a window zoom level of 90% (or whatever `Ctrl`+`-` once is). My monitor is a Dell 1980 x 1200 screen.
![Screenshot from 2020-06-11 10-14-31](https://user-images.githubusercontent.com/6289786/84396567-61295c00-abcc-11ea-8d5f-b77e96e3624a.png)

**Comment by EmbeddedBacon** [comment]
I am running VS Code on a Windows 10 machine and remote ssh into a Linux box, resolution is 3840x1600 on Windows 10,  I didn't see any HexEditor settings other than "Max File Size", so I am listing some settings I have that I think might be useful

```
  "window.zoomLevel":     -0.725,
  "window.titleBarStyle": "custom",

  "editor.fontFamily":               "Droid Sans Mono",
  "editor.fontSize":                 13,
  "editor.tabSize":                  4,
  "editor.useTabStops":              false,
  "editor.detectIndentation":        false,           // set to false so `editor.tabSize` and `editor.insertSpaces` will be detected based on the file contents
  "editor.showFoldingControls":      "always",
  "editor.rulers":                   [80,120,150],
  "editor.suggestSelection":         "first",
  "editor.minimap.enabled":          true,
  "editor.find.autoFindInSelection": "always",
  "editor.renderWhitespace":         "selection",
  "editor.columnSelection":          false,
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "comment",
        "settings": {
          "fontStyle": ""
        }
      },
    ]
  },

  "workbench.editor.closeOnFileDelete":          false,
  "workbench.colorTheme":                        "Cobalt2",
  "workbench.startupEditor":                     "newUntitledFile",
  "workbench.editor.enablePreview":              true,
  "workbench.editor.enablePreviewFromQuickOpen": false,
  "workbench.colorCustomizations": {
    "editor.selectionHighlightBorder":       "#ff0000",    // "#ffffff",
    // "editor.findMatchBackground":             "#6c7d9a",
    "editor.findMatchBackground":            "#000000",
    "editor.findMatchBorder":                "#ff0000",
    "editor.selectionBackground":            "#47828f",
    "editor.selectionHighlightBackground":   "#ac2121"
  },
```

**Comment by lramos15** [comment]
Can you try running with GPU optimizations disabled to see if this helps. I'm still trying to investigate this issue. Try `code-insiders --disable-gpu` if you're on insiders or `code --disable-gpu` if you're not. This might be a general electron issue as we have seen this issue in VS Code (https://github.com/microsoft/vscode/issues/84154) and I'm not doing anything fancy here with the font rendering.

**Comment by EmbeddedBacon** [comment]
I still see even with the --disable-gpu

![image](https://user-images.githubusercontent.com/42427056/85904943-e01eb700-b7be-11ea-8adf-fbe0c7e65332.png)

**Comment by EmbeddedBacon** [comment]
VS Code 1.47.0 came out and long with it a new version of HexEditor v1.1.0 came out also.  Though, the font looks a bit better, the font is still fuzzy compared to source files.  Good enough for now.

**Comment by lramos15** [comment]
I'm not sure of another solution for this. I just implemented the solution that VS Code does. If it still bothers you feel free to open the issue again and I'll try to investigate more
