### ISSUE TITLE
When viewing a binary file that is larger than 1MB - 16 bytes, larger than (1024*1024)-16, incorrect zero bytes are shown for the last paragraph.

### ISSUE THREAD

**Issue by AshleyT3** [microsoft/vscode-hexeditor#353]
Steps (one example):
1. Create binary file that is (1024*1024*3) + 3 bytes... use non-zero byte values to identify the issue.
2. Open the file in the hex editor.
3. On repro, notice bytes for the last paragraph of each 1MB block are zero bytes when, in the file, they are non-zero.

Example from tail end of 3MB + 3 byte file...
![image](https://user-images.githubusercontent.com/32182932/163067942-64778cd0-54cc-478c-bb0f-7d2809234e2c.png)

Example from 1MB boundary of 3MB file...
![image](https://user-images.githubusercontent.com/32182932/163069185-6a6f303c-9379-4a77-9d3e-2182a231a186.png)

Version: 1.66.1 (system setup)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:50:12.141Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by jancaussyn** [comment]
I find this phenomenon before every multiple of 0x20000, actually.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-hexeditor/issues/346

**Comment by connor4312** [comment]
This didn't get published previously, I just now kicked off a build for it.
