### ISSUE TITLE
Selecting from right to left shows wrong output in Data Inspector

### ISSUE THREAD

**Issue by MdFahimulIslam** [microsoft/vscode-hexeditor#354]
### Steps to reproduce
1. Set bytes per row as 6. (may not be necessary step, but I did it)
2. Select two bytes by dragging mouse from right to left (or using keyboard's shift+left arrow)

You'll note that the Data Inspector shows wrong result when dragged from right to left.

![image](https://user-images.githubusercontent.com/24982795/163598095-9b9a6516-e107-40b5-9c1e-6e653450da3f.png)

**Comment by connor4312** [comment]
The data inspector shows information about the focused line. In the first screen, you have `0x64` focused, and in the second screenshot `0x80` is selected.
