### ISSUE TITLE
Hex Editor Data Inspector can not copy

### ISSUE THREAD

**Issue by dujun861** [microsoft/vscode-hexeditor#355]
Issue Type: <b>Bug</b>

select something such as int64 etc. in Data Inspector，it can not be copyed to calc.  (vscode 1.66.0, OS: win7 x64 pro)

Extension version: 1.9.5
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by saloid** [comment]
I'm using memory view in [cortex debug](https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug) and I can't copy anything (editor opened as read-only binary file).
![image](https://user-images.githubusercontent.com/22222390/164228487-e355cb94-d744-495f-8fcf-7686d82d3a56.png)

**Comment by hakanai** [comment]
Same deal here, doesn't work on any normal file either.

The extension page says it _should_ work:
> Editing with undo, redo, copy, and paste support

**Comment by lramos15** [comment]
![Recording 2022-11-30 at 09 19 16](https://user-images.githubusercontent.com/4544166/204819841-ce21b636-88b9-4953-98a5-53c452b9a70d.gif)

It seems to be working for me are you seeing something different?

**Comment by hakanai** [comment]
Clearly. Mine just pastes whatever was previously in the clipboard every time I paste.

https://user-images.githubusercontent.com/43236/204916005-d23a56b3-0ed5-44d0-940a-e40f0d083fa4.mp4

**Comment by hakanai** [comment]
Maybe it's a version difference or one of us has a different hex editor plugin, because it turns out there are a few.

![image](https://user-images.githubusercontent.com/43236/204916460-62fffc35-1efc-4fc2-a6fe-c3a4221c4104.png)

**Comment by lramos15** [comment]
We're using the same version, but you're using the VS Code native copy which we cannot intercept. So you have to use the keybindings of `Ctrl + C ` and `Ctrl +V` to copy and paste. The hex view is copied as base64 and can be confusing, we have an issue tracking that though

**Comment by hakanai** [comment]
Oof. Designing an application to have multiple Copy actions where activating them in different ways causes different results is bad design in my book. Sounds like something VSCode itself has to fix.

**Comment by lramos15** [comment]
Yeah that's being tracked here https://github.com/microsoft/vscode-hexeditor/issues/341#issuecomment-1106707268 will close for now, and see if there is a way for us to override the native copy menu
