### ISSUE TITLE
Insert & Delete Not Supported

### ISSUE THREAD

**Issue by jimwheeler** [microsoft/vscode-hexeditor#366]
Forgive me if someone has already entered this or maybe I am just missing how to accomplish this but I cannot insert new bytes or remove bytes.  I seem to be able to only change the value for existing bytes.

This is an absolute critical requirement.  This extension is worthless without that ability.

**Comment by doug-a-brunner** [comment]
Seems like it's now impossible to *not* insert bytes, or to delete ones that were added?
