### ISSUE TITLE
Hex editor find usage?

### ISSUE THREAD

**Issue by glenneuropa** [microsoft/vscode-hexeditor#368]
![photo](https://user-images.githubusercontent.com/110130557/181364052-424f80e0-5c4e-4b5c-a653-9f974e063dff.png)

In this photo, when looking for any hex code like 0x6A, it doesn't find that value when entering '6A' into the find field. Is there some additional format or setting needed to have the find work on hex values?

**Comment by lramos15** [comment]
Images can be encoded in a variety of ways and just finding and replacing bytes isn't necessarily the easiest way to image edit. You probably want something like https://marketplace.visualstudio.com/items?itemName=Tyriar.luna-paint for image editing

**Comment by glenneuropa** [comment]
No, this is incorrect. I am trying to find data in a binary file and only provided the image as an example. You can use an .exe file if you want - the problem is that for *any* binary file, the 'find' command does not work. I am being optimistic in assuming I am using the wrong format in the find string for the text box.

**Comment by glenneuropa** [comment]
You are correct sir, thank you.

**Comment by lramos15** [comment]
New version should be released please let me know if this is still not working for you

**Comment by glenneuropa** [comment]
I'm still seeing the same issue, v1.9.8. Restarted VSC. Uninstalled and re-installed, same result.

**Comment by lramos15** [comment]
Your issue seems different then. Do you mind providing a gif?

**Comment by glenneuropa** [comment]
No problem! If you need anything else, let me know. I'm using the photo above with

Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

![VSCerror](https://user-images.githubusercontent.com/110130557/181584805-d53fef31-0679-42f4-9dbf-cc2c220fca30.png)

**Comment by lramos15** [comment]
You need to check the little hex icon in the find widget. The 0101 file icon on the right there

**Comment by connor4312** [comment]
Maybe we should add some heuristic--if no results are found and the input looks like it's valid hex, we suggest turning on binary search mode. Though in this case there were results for the characters "5F" so it wouldn't have helped.

**Comment by lramos15** [comment]
> Maybe we should add some heuristic--if no results are found and the input looks like it's valid hex, we suggest turning on binary search mode. Though in this case there were results for the characters "5F" so it wouldn't have helped.

I definitely think it's a bit more confusing what's going on now that the default for decoded text is not to show it off to the right. So they're matching the hover widget

**Comment by connor4312** [comment]
> the default for decoded text is not to show it off to the right

Is it? I was pretty sure we still showed decoded text by default unless the user was on a narrow display, which does not appear to be the case here.

**Comment by glenneuropa** [comment]
That's correct - I forgot to enable it this time. It does work, looks good!
