### ISSUE TITLE
Breakpoints don't bind

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode-hexeditor#374]
Following the instructions in [CONTRIBUTING.md](https://github.com/microsoft/vscode-hexeditor/blob/main/CONTRIBUTING.md#build-and-run), I execute `npm run watch` and then hit F5 to "Run Extension". No breakpoints anywhere can be bound. Debug diagnostics suggest two things: that `"sourceMap": true` be in `tsconfig` (it's already there) and that I remove the `outFiles` section in `launch.json`.

The `outFiles` section seems wrong as it points to "${workspaceFolder}/out/**/*.js" which is not a directory. Anyway, removing it makes no difference and the diagnostics still says "It looks like you narrowed the `outFiles` in your launch.json".

**Comment by connor4312** [comment]
This is a result of us using [Linaria](https://github.com/callstack/linaria) which, in our version, doesn't correctly adjust sourcemap locations. However we're on an old beta from them and there's a good chance they fixed that if we upgrade...

**Comment by lramos15** [comment]
Looks like https://github.com/callstack/linaria/pull/991 might have fixed it. Will try upgrading

**Comment by lramos15** [comment]
@connor4312 Do you have any free time and want to look into upgrading linaria together? I don't know if it just changed a lot but I cannot get the code to compile with the latest version

**Comment by connor4312** [comment]
Hm, I'll give it an initial spin today
