### ISSUE TITLE
Mouse selection has two selection mechanisms

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode-hexeditor#375]
When I drag the mouse to select, It seems there's two selection mechanisms at play; the intended one  (light blue) which selects only bytes, and another one (dark blue) which is simply selecting all text, wrapping around outside the bytes display:
![6cfc0b29-2e0d-4b58-ab5c-9b157920f078](https://user-images.githubusercontent.com/26465923/183472692-49f89799-a39a-499b-9163-9527fc0ad30e.gif)

Clicking outside the editor area will clear the dark blue selection and expose the light blue one.

Double-clicking on a byte also makes the dark blue selection show up.

Selecting with the keyboard works just fine.

**Comment by chrmarti** [comment]
Still seeing this with 1.9.8.

**Comment by chrmarti** [comment]
https://user-images.githubusercontent.com/9205389/194230254-2660fc64-e633-4448-bddf-b3aec256e94d.mov

Version: 1.72.0-insider (Universal)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:18:32.134Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**Comment by lramos15** [comment]
This should be fixed just a release did not go out. Just released 1.9.9

**Comment by rzhao271** [comment]
Verified
TIL I have to shift+click in order to select multiple bytes
