### ISSUE TITLE
M and N transposing on opening Uint8Array

### ISSUE THREAD

**Issue by tom-mathias-slalom-pol** [microsoft/vscode-hexeditor#379]
When I debug a jest test and set a breakpoint after the line of code:

`const asciiMN = Uint8Array.from([0x4D, 0x4E])`

The locals window contains a Uint8Array containing [77, 78], however, when I used the context menu to select View Binary Data, in the memory.bin, the contents are
`4E 4D`, which is decoded to `N M`

**Comment by connor4312** [comment]
This was actually a (rather embarrassing) bug in the js debugger https://github.com/microsoft/vscode-js-debug/pull/1376

Please grab the [nightly debugger build](https://github.com/microsoft/vscode-js-debug#nightly-extension) for the fix
