### ISSUE TITLE
where is the Insert Mode？

### ISSUE THREAD

**Issue by AshleyKwan** [microsoft/vscode-hexeditor#380]
I tired use Insert key to switch the mode, but it still in replace mode. how can I switch to insert mode?

**Comment by jwr12135** [comment]
Inserting bytes is not possible yet for this editor. There is already an issue (https://github.com/microsoft/vscode-hexeditor/issues/71) open for this though, and you can see the progress there. The editor is also missing the ability to delete bytes as well.

**Comment by lramos15** [comment]
duplicate #71
