### ISSUE TITLE
EACCESS error opening file when lacking write permission

### ISSUE THREAD

**Issue by mpictor** [microsoft/vscode-hexeditor#385]
This is somewhat related to #180 but more severe: I am unable to view the file.

Given a file with mode `0o444` (aka `r--r--r--`, no write access) I an unable to view the file. Instead, an error pops up:

```
Unable to open 'file.name'
EACCESS: permission denied, open '/path/to/file.name'
```

### Desired behavior:

If it fails to open read-write, it should try again readonly and disallow edits.

**Comment by lramos15** [comment]
We don't currently have a readonly mode which is why this doesn't work. #180 would unblock this too
