### ISSUE TITLE
Hexdump of clipboardtext

### ISSUE THREAD

**Issue by Christian-Schulz** [microsoft/vscode-hexeditor#40]
I need the ability to showing hexdump of text from the clipboard.
Without having to save it in a file first.

**Comment by mika76** [comment]
This is a great idea and it would be necessary to differentiate whether you're dumping actual binary/string or a hex string - the way http://hexed.it does it is good :)

**Comment by lramos15** [comment]
I think this is out of scope for what we're aiming to do with the hex editor. I think saving a temp file and deleting it after will be the easy solution for this and doesn't involve the extra complexities that would come with this feature. The hex editor does now support copy and paste within it as of 1.2.0 though.
