### ISSUE TITLE
Feature request: Octal representation of the selected byte in the data inspector

### ISSUE THREAD

**Issue by brabli** [microsoft/vscode-hexeditor#405]
Hi, currently the data inspector shows several different representations of the selected byte and it's following bytes, but does not show any octal values at all which is a shame.

I think adding the octal value of the currently selected byte to the data inspector would be a small but useful addition, I would be very happy to see this added.

**Comment by connor4312** [comment]
Added in https://github.com/microsoft/vscode-hexeditor/pull/410
