### ISSUE TITLE
Copy hex codes as string

### ISSUE THREAD

**Issue by Marterido** [microsoft/vscode-hexeditor#416]
Is it possible to copy the hex as a string?

I have read in [this](https://github.com/microsoft/vscode-hexeditor/issues/341#issuecomment-1046079416) comment that the copied code is encoded in base64, but I would like to get the hex codes as a string. Is this somehow possible?

**Comment by lramos15** [comment]
This is not currently possible but something we are looking to improve. Will close in favor of tracking #341
