### ISSUE TITLE
[feature] option to tell VS Code to skip "The file is not displayed in the text editor because it's either binary..." dialogue and directly open the file with Hex Editor

### ISSUE THREAD

**Issue by verhovsky** [microsoft/vscode-hexeditor#420]
When I click on an executable I get this dialogue
<img width="515" alt="Screenshot 2023-03-10 at 11 51 47 AM" src="https://user-images.githubusercontent.com/5687998/224297978-79cac52c-cb5c-4a8e-abe0-3c3e21234e8a.png">
I have to click "Open Anyway" then I have to click "Hex Editor". Can I configure VS Code to just skip the dialog and fallback  binary files with Hex Editor? It would be immediately obvious to me that the file is a binary file if it got opened in Hex Editor instead of showing me a dialog saying that.

I can choose Hex Editor as the default view for a given file extension if the file has a file extension, but in this case I'm clicking on an executable that doesn't and what if I don't want to do this for every single file extension. Also if I click away in the file tree I see the dialog when I click back on the file.

**Comment by lramos15** [comment]
`workbench.editor.defaultBinaryEditor` is the setting you're looking for.
