### ISSUE TITLE
Can't open file whose path contains CN charactors.

### ISSUE THREAD

**Issue by narulmcto** [microsoft/vscode-hexeditor#421]
Can't open file whose path contains CN charactors.

**Comment by narulmcto** [comment]
For example : "E:\相关\\locales\lan.pak"

**Comment by connor4312** [comment]
I cannot reproduce this. Please provide more info about what you're seeing:

![image](https://github.com/microsoft/vscode-hexeditor/assets/2230985/b7f14c1b-c52c-43ce-9a6e-bc1192c59da5)

**Comment by narulmcto** [comment]
邮件已收到，我会尽快查看
