### ISSUE TITLE
A file cannot be opened

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode-hexeditor#422]
I don't know what the cause for this error is as Hex Editor doesn't unveil the OS error code:

![grafik](https://user-images.githubusercontent.com/9283914/228079103-6f8df8f1-77a8-44a3-8029-5679e3ae3315.png)

While the Hex Editor can open some files, it cannot open particular others (see above).

<br/>

Here's the file that cannot be opened by Hex Editor (contained in the ZIP file):

[Silence.zip](https://github.com/microsoft/vscode-hexeditor/files/11083466/Silence.zip)

**Comment by lramos15** [comment]
Ah! It's because this file only has read permissions and we don't have a read only mode therefore we require read and write perms on the file a simple `chmod` or permissions adjustment should fix this.

**Comment by SetTrend** [comment]
Read-only permissions of a file in a ZIP file ..? Are you sure that's the reason? On my machine the file comes with full read/write access.

**Comment by lramos15** [comment]
> Read-only permissions of a file in a ZIP file ..? Are you sure that's the reason? On my machine the file comes with full read/write access.

When I unzip the file in your zip it says it is read only. When I chmod it to be read write it opens with no error

**Comment by connor4312** [comment]
We support readonly filesystems but maybe we don't check individal file permissions correctly. Should be an easy fix.

**Comment by SetTrend** [comment]
Ah, now I get it: The file isn't write protected (read-only file attribute is not set), yet NTFS rights deny write access to users and administrators. It's new to me that NTFS rights are written to files in a ZIP archive.

**Comment by connor4312** [comment]
PR welcome here, the [NativeFileAccessor](https://github.com/microsoft/vscode-hexeditor/blob/main/src/fileSystemAdaptor.ts#L134) should have the optional `isReadonly?: boolean` from the `FileAccessor` so that the UI display is right, and the FileHandleContainer should use the correct flags to open it

https://github.com/microsoft/vscode-hexeditor/blob/acb4eb481fca73d3dcd90092ae21059f5865d033/src/fileSystemAdaptor.ts#L105

**Comment by connor4312** [comment]
A PR was merged for this

**Comment by Mola19** [comment]
I am currently having thee same issue. Text Editor works, but Hex Editor gives me an `EPERM: operation not permitted, open [filename]`.

OS: Windows 10
VSC: 1.99.3
Hex Editor: 1.11.1
