### ISSUE TITLE
Feature Request: Display values in status bar in hexadecimal

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode-hexeditor#424]
The status bar information is only displayed in decimal. This way it's hard to compare offsets and ranges with hexadecimal data:

![Hex Editor selection](https://user-images.githubusercontent.com/9283914/228084895-78726e57-91cd-4615-b636-af81751b5bde.png)

Please, display byte offset and selection length in hexadecimal, too.

**Comment by connor4312** [comment]
Done in https://github.com/microsoft/vscode-hexeditor/pull/486
