### ISSUE TITLE
Hex Editor displays unnecessary notification when a previously-opened file is deleted

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-hexeditor#428]
1. Open a file in the hex editor
2. Close the hex editor
3. Delete the file
4. :bug: get this warning from the hex editor:

![image](https://user-images.githubusercontent.com/30305945/228932637-8f7c5067-b522-4ec9-bae7-ca6bdc2ce25e.png)

**Comment by cyjohnson-ss** [comment]
Confirmed

**Comment by AaronRidoutAE** [comment]
There is another two parts to this issue that I see.

1. Even though the file is closed, this still pops up and the 'Close Editor' button closes the current window - not the offending ine (which in my case is already closed!). Please only close the offending window, not the current one!
2. The pop up does not say which file it is warning about - I have many files open and one of them is transitory (being built in my case). Please add the filename to the pop-up!

**Comment by TheMatt2** [comment]
Confirmed as well.

1. Open a file in the hex editor
2. Close the hex editor
3. Open a different file
4. Modify file
5. Delete original file

If you click "Overwrite", nothing happens. The file is not restored.
If you click "Close Editor" then the other file is closed.

**Comment by Dream-Painter** [comment]
Confirmed, and it even happens multiple times.
I had a temp file, which is created and deleted multiple times, and I got multiple popups after opening it once.
