### ISSUE TITLE
Navigation on large files is very slow

### ISSUE THREAD

**Issue by felixcollins** [microsoft/vscode-hexeditor#436]
I open a 1MB bin file and is very slow to get around. Opening the same file in notepad and navigation is instant. I understand that the extension is doing more than just displaying the file as ascii but it should be able to cope better. sliding the scroll bar chokes it.

**Comment by connor4312** [comment]
This is something I've been wanting to fix for a while. We have some overhead from React/Recoil here, but even extracting those and doing raw DOM manipulation, scrolling is pretty laggy. This is also common on other web-based hex editors I was experimenting with. I think we just need to use the canvas here. That will require some refactoring but should be pretty speedy.
