### ISSUE TITLE
Search not re-evaluated after file modification

### ISSUE THREAD

**Issue by josephH00** [microsoft/vscode-hexeditor#444]
When a file opened in the hex editor is changed from either inside or outside VS Code, the search results are not re-evaluated and retain the results and position from the older file. I've attached two screenshots below showing the behavior.

Before modification:
<img width="1064" alt="old" src="https://github.com/microsoft/vscode-hexeditor/assets/12785608/ef0deb56-a028-4309-99dd-8e2bf4d974eb">

After modification:
<img width="1064" alt="new" src="https://github.com/microsoft/vscode-hexeditor/assets/12785608/733dd470-f9c9-4b60-9c8b-b27689de4e92">

**Comment by karthiknadig** [comment]
I don't see a pre-release version for this with the fix.

**Comment by DonJayamanne** [comment]
@mjbvz out of curiosity, where did you get the VSIX for this?

**Comment by mjbvz** [comment]
@DonJayamanne I add verified when I start verifying so others don't grab them. In this case I couldn't verify so I then unmarked it

**Comment by karthiknadig** [comment]
This still exists using the current main branch build:
![image](https://github.com/microsoft/vscode-hexeditor/assets/3840081/5d19588e-bb18-4e02-ae75-8dd33b3679df)

It looks like the search does not reevaluate as you type as well.

**Comment by aiday-mar** [comment]
We probably need a new label of type `under-verification` so the issue is not verified in parallel by two different people. I will add that label. 

@connor4312 I am pinging about the milestone for this issue. We have branched off from the `main` branch recently. Would you like to make this issue a candidate or move it out to the `March 2024` milestone?

**Comment by connor4312** [comment]
> We probably need a new label of type under-verification so the issue is not verified in parallel by two different people. I will add that label.

@aiday-mar the practice is to add `verified` when you start verifying and remove it if verification fails. That will also prevent the issue showing up in queries
