### ISSUE TITLE
find widget invisible when search button is down

### ISSUE THREAD

**Issue by OrzTanLaLa** [microsoft/vscode-hexeditor#447]
Nothing happens after clicking Search in the menu. Only when ctrl+f is down does find widget appear.
https://github.com/microsoft/vscode-hexeditor/blob/d59d54e3a6cc471791f0967634ea0226e7fd8cbf/media/editor/findWidget.tsx#L152C2-L164C9
Easy to fix.

**Comment by connor4312** [comment]
Which "Search" menu are you clicking?
