### ISSUE TITLE
Search for bytes, based on byte values, or byte patterns

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode-hexeditor#45]
This is a feature request.

Currently, we have the ability to read the bytes of a file, based on the memory offset and the decoded text.

I would like to be able to search for particular bytes in the file, to be able to pinpoint where in the file are byte patterns found. This can be helpful for viewing data chunks and data wrappers where a particular byte pattern is used commonly in the file, making it easier to navigate and locate the data needed.

It would be even wonderful, as another feature, if we could search by decoded text and look for the matching byte values in the hex editor. I don't know if Regular Expressions can work for decoded text, but 'tis a dream.

**Comment by Surendrajat** [comment]
I always use the bytes pattern feature. Super useful. A hex editor is kinda incomplete for me if I can't find a given pattern with masks like 4d cf ?? ?? 23 49. Presently using IDA freeware for only this :). Will really like to use my VS Code for binary patching and all.

**Comment by lramos15** [comment]
This will most likely be a large focus of the July iteration once editing has been implemented.

**Comment by cole-anstey** [comment]
Hi, a really nice search feature would be an option to persist one or more byte sequences with a customisable colour and tooltip name to your settings file.
Whenever the hexeditor is opened it would then use these stored byte sequences to automatically highlight the binary for you.
Maybe it could be added to the existing "workbench.editorAssociations"; so you could have different sequences per file?
