### ISSUE TITLE
Overwrite option doesn't work when a opened file is deleted

### ISSUE THREAD

**Issue by lorsanta** [microsoft/vscode-hexeditor#454]
Steps:
- Open a file in the hex editor
- Replace a byte in the file without saving
- Delete the file from terminal
- When a dialog shows up click **Overwrite**
- Reopen the file

Instead of containing the expected data, the file now contains a sequence of zeros followed by the new byte.

The problem seems to be caused by how `HexDocumentModel.save()` is implemented. When a file is deleted, the model should rewrite the entire file instead of selectively writing to it.

Maybe a possible fix would be to add a `isInConflictState` attribute to the model?

**Comment by zet23t** [comment]
This bug is even more annoying: 

- Open file in hex viewer
- Close file in hex viewer
- Delete file
- Notification spam that the file was deleted and if you want to close the file or overwrite it
- Closing the window closes just the current tab. It does nothing when no more files could be closed.

**Comment by alexr00** [comment]
@connor4312 how should this be verified? I can repro the original issue, but I don't see a pre-release version of the extension to install.

**Comment by connor4312** [comment]
We just published a new version of the hex editor
