### ISSUE TITLE
When viewing hex values, there should be a way to select multiple hex values for copying

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode-hexeditor#46]
Currently, you can only select 1 byte value at a time, both in the Hex Value (center column) and in the Decoded  Text (right column). I don't know what the center column is called, and I wished there is a name for it. ("Memory"?)

![image](https://user-images.githubusercontent.com/6444116/84584033-c0a28a00-adcd-11ea-866d-ea710198a2f9.png)

You cannot copy hex values from the Data Inspector, the Hex Values, and the Decoded Text. If we are able to select multiple byte values for copying, then the Data Inspector and the Decoded Text should also be allowed to do copy operations for multiple byte values.

**Comment by lramos15** [comment]
Fixed https://github.com/microsoft/vscode-hexeditor/pull/98
