### ISSUE TITLE
UTF-8 data on the data inspector can decode text longer than one byte

### ISSUE THREAD

**Issue by juls0730** [microsoft/vscode-hexeditor#462]
## Issue summary
If you have bytes that form text in some sort of bespoke two-byte UTF-8, the data inspector will give you incorrect data.

## Environment
- VSCode Version: 1.83.1 commit f1b07bd25dfad64b0167beb15359ae573aecd2cc
- Extension Version: v1.9.12
- Operating System: Linux

## Steps to reproduce
1. open a file with the hex editor
2. Write two bytes, in my case, 0xDD and 0x9F
3. Highlight the 0xDD bytes
4. Decoded text shows `..`, but the data inspector shows `ݟ` 

**Expected behavior:** The data inspector should show nothing, as 0xDD corresponds to nothing in UTF-8
**Actual behavior:** The data inspector shows `ݟ` for the UTF-8 data

**Comment by connor4312** [comment]
`0xDD 0x9F` is a code point for U+075F, which is a [valid character](https://www.unicode.org/charts/PDF/U0750.pdf).

The UTF-8 view is intended to show the UTF-8 code point starting at the selected byte, when valid. That seems to be working based on your description.

**Comment by juls0730** [comment]
@connor4312 oh, so it is, I'm so sorry for wasting your time.
