### ISSUE TITLE
Copy, Cut, Paste do not work

### ISSUE THREAD

**Issue by Lassebq** [microsoft/vscode-hexeditor#474]
OS: Arch Linux
Display server: Wayland, Xorg
Desktop environment: GNOME

Neither context menus nor shortcuts have any effect on the edited area or the clipboard's contents

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/141080

**Comment by Lassebq** [comment]
Huh? No, the issue is within the extension. Any plain text document utilizes clipboard properly and context menus *do* work.
