### ISSUE TITLE
[Feature request] Add in data inspector ULEB128 and SLEB128

### ISSUE THREAD

**Issue by jogo-** [microsoft/vscode-hexeditor#485]
Show in data inspector missing large integer formats as ULEB128 and [LEB128](https://webassembly.github.io/spec/core/binary/values.html#Integers) (Little Endian Base 128)

**Comment by jogo-** [comment]
🤔 Maybe using _WASM based [Little Endian Base 128](https://en.wikipedia.org/wiki/LEB128) varint encoding / decoding, supporting the full (u)int64 range_ https://github.com/thi-ng/umbrella/tree/develop/packages/leb128

**Comment by connor4312** [comment]
It should be easy enough to implement in plain JS/TS, their [wasm library](https://github.com/thi-ng/umbrella/blob/develop/packages/leb128/zig/leb128.zig) is nothing magic

**Comment by jogo-** [comment]
Decoding ULEB128 and LEB128 as a full 128 bit integers will be the biggest challenge, as the largest **BigInt** integer type is limited too.
Number.MAX_SAFE_INTEGER = 9007199254740991
Number.MIN_SAFE_INTEGER = -9007199254740991
Or I could try first to decode ULEB128 and LEB128 as sets of up to 16 bytes.
@connor4312 What is your opinion?

**Comment by connor4312** [comment]
[BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) is an arbitrary precision integer and is supported everywhere that VS Code runs
