### ISSUE TITLE
Bug: Extension Name

### ISSUE THREAD

**Issue by Malix-off** [microsoft/vscode-hexeditor#487]
https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor
description == "`%description`"
![image](https://github.com/microsoft/vscode-hexeditor/assets/76160668/dba09de8-5a22-4414-8114-7bb1a0107c0b)

**Comment by connor4312** [comment]
Dupe of https://github.com/microsoft/vscode-hexeditor/issues/484
