### ISSUE TITLE
Support IDA style masked bytes search & replace

### ISSUE THREAD

**Issue by Surendrajat** [microsoft/vscode-hexeditor#49]
I know it's very early but I'm excited about this very useful extension and therefore this feature request. I'd like to search for a byte pattern as suggested in #45 with regex but more precisely in IDA style byte masking with `??`. As it's a very common format to share malware patterns and all.
Example pattern: `3d ac ?? 25 9d ?? ?? 2f`.

**Comment by lramos15** [comment]
I think this is an interesting idea and almost feels more useful than just a regex. I believe that once search support is added this IDA style byte masking could just be converted to a regex in the background which means it shouldn't require too much extra implementation work as well

**Comment by tommai78101** [comment]
The regex I proposed in #45 was for decoded text. I believed both methods, the `??` and regex searching will be useful for respective data viewing and editing for memory bytes and decoded text.
