### ISSUE TITLE
Rendering should be virtual wrt viewport

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-hexeditor#5]
Testing https://github.com/microsoft/vscode/issues/98980

You should be able to use our list widget for this. It seems we're rendering wayyy more than necessary and I get a lot of blank frames when scrolling around.

**Comment by lramos15** [comment]
This was discussed briefly and I think it was just stated that it was too intertwined with the core of VS to easily utilize in the hex editor. I would be happy to discuss it more with you if you have any further knowledge about how that could easily be done, I would be happy to discuss it as my implementation does do some basic chunk rendering which does have a decent buffer outside the viewport.

**Comment by joaomoreno** [comment]
We'd have to _weed it out_ but it is feasible! We even have [paging capbilities](https://github.com/microsoft/vscode/blob/master/src/vs/base/browser/ui/list/listPaging.ts) which simply calls for pages to load, as the list scrolls up and down.

**Comment by rebornix** [comment]
![recording](https://user-images.githubusercontent.com/876920/83549337-056b1e80-a4ba-11ea-8e1e-242c91b95673.gif)

I'm seeing a lot of blank frames when scrolling even though the file is relatively small (2k loc), which makes navigating in the document really hard.

If adopting list view is hard, I think we should at least add some gpu optimization to the rendering.

**Comment by rebornix** [comment]
>  I think we should at least add some gpu optimization to the rendering.

I took it back, the root cause is forced reflow -->

![image](https://user-images.githubusercontent.com/876920/83549807-bbcf0380-a4ba-11ea-9bbf-3ace9960215f.png)

```ts
private populateHexAdresses(rowData: VirtualizedPacket[]): void {
        const hex_addr = document.getElementById("hexaddr");
        const offset = rowData[0].offset;
        const addr = document.createElement("div");
        addr.className = "row";
        addr.setAttribute("data-offset", offset.toString());
        addr.innerText = pad(offset.toString(16), 8).toUpperCase();
        hex_addr!.appendChild(addr);
        this.rows[0].set(offset.toString(), addr);
        // We add a left px offset to effectively right align the column
        addr.style.left = `${addr.parentElement!.clientWidth - addr.clientWidth}px`;
        this.translateRow(addr, offset);
    }
```

Suggestions:

* hold a reference to `hexaddr` DOM node
* cache its width
* listen to window size change and then update the cache (and also rerender the viewport if necessary)

I think this will remove most force reflow and reduce this issue by a ton.

**Comment by connor4312** [comment]
We're now virtual
