### ISSUE TITLE
Incorrect adresses for Intel and motorola formats

### ISSUE THREAD

**Issue by fili28** [microsoft/vscode-hexeditor#51]
The memory offset column always starts from 0000 0000, which is true for bin files, but hex files in intel and motorola format can have blocks, which starts at later adresses. Can be the real offset shown?

**Comment by lramos15** [comment]
Do you have an example file I may use? I want to try it in other hex editors and see how they handle it. Currently the offset is just a simple counter.

**Comment by tommai78101** [comment]
@lramos15 Not sure if this is helpful, but there is a pretty documentation of the Intel HEX and Motorola file formats:

https://www.keysight.com/main/editorial.jspx?ckey=25084%3Aatg%3Afaq&id=25084%3Aatg%3Afaq&nid=-35181.0.00&lc=ger&cc=DE

Small example of Motorola s record:

```
S00B00004441544120492F4FF3
S113000000FF0004000400040004000400040004D1
S113001000040004000400040004000400040004BC
S113002000040004000400040004000400040004AC
S1130030000400040004000400040004000400049C
S1130040000400040004000400040004000400048C
S1130050000400040004000400040004000400047C
S1130060000400040004000400040004000400046C
S1130070000400040004000400040004000400045C
S1130080000400040004000400040004000400044C
S1130090000400040004000400040004000400043C
S11300A0000400040004000400040004000400042C
S11300B0000400040004000400040004000400041C
S11300C0000400040004000400040004000400040C
S11300D000040004000400040004000400040004FC
S11300E000040004000400040004000400040004EC
S11300F000040004000400040004000400040004DC
```

Small example of Intel Hex record.

```
:020000020000FC
:020000040000FA
:1000000000FF0004000400040004000400040004D5
:1000100000040004000400040004000400040004C0
:1000200000040004000400040004000400040004B0
:1000300000040004000400040004000400040004A0
:100040000004000400040004000400040004000490
:100050000004000400040004000400040004000480
:100060000004000400040004000400040004000470
:100070000004000400040004000400040004000460
:100080000004000400040004000400040004000450
:100090000004000400040004000400040004000440
:1000A0000004000400040004000400040004000430
:1000B0000004000400040004000400040004000420
:1000C0000004000400040004000400040004000410
:1000D0000004000400040004000400040004000400
:1000E00000040004000400040004000400040004F0
:1000F00000040004000400040004000400040004E0
:020000020010EC
:1000000000040004000400040004000400040004D0
:1000100000040004000400040004000400040004C0
```

**Comment by lramos15** [comment]
After discussion and investigation I don't think it would be worth adding custom parsing directly in the editor for something specific like Intel and Motorola formats as we're aiming for a general all around binary file viewer / editor. The real solution is probably to allow custom parsers and an API for modules on top of the editor similar to what @NotWearingPants outlined in https://github.com/microsoft/vscode-hexeditor/issues/50
