### ISSUE TITLE
Add "Right Click -> Copy Address" feature when right-clicking on a byte

### ISSUE THREAD

**Issue by DeflateAwning** [microsoft/vscode-hexeditor#519]
I want to be able to copy the address of the currently-selected byte when I right-click on it.

I propose the following two additions to the right-click context menu:

1. Copy Address as Dec
2. Copy Address as Hex

The right-click menu is currently very empty, so I see no downside to adding this feature.

**Comment by tomilho** [comment]
I can work on this, but I am not sure how it will impact #498. I will add them as separate commands for now.

**Comment by connor4312** [comment]
Publishing in https://github.com/microsoft/vscode-hexeditor/pull/541

**Comment by DeflateAwning** [comment]
Fantastic news, thank you!
