### ISSUE TITLE
Mix-up between links to #503 and #513 in Release Notes from the Extension/Marketplace

### ISSUE THREAD

**Issue by jogo-** [microsoft/vscode-hexeditor#525]
In the Release Notes from the Extension/[Marketplace](https://marketplace.visualstudio.com/items/ms-vscode.hexeditor/changelog), there's a mix-up between links to https://github.com/microsoft/vscode-hexeditor/pull/503 and https://github.com/microsoft/vscode-hexeditor/pull/513.
Here in the repo, the CHANGELOG.md is correct but not really complete.

**Comment by connor4312** [comment]
Publishing in https://github.com/microsoft/vscode-hexeditor/pull/541
