### ISSUE TITLE
why can the dataInspector only parse one byte? 

### ISSUE THREAD

**Issue by Little-Polaris** [microsoft/vscode-hexeditor#530]
Many times i hope to check what number my bytes represent in int32 or float32, but the dataInspetor can only show the only one byte my mouse points to. it's annoiying and hope you can add the feature in future version

**Comment by lramos15** [comment]
It reads out to the right. So if your mouse is on a byte, it will read 3 additional bytes to the right to show int32.

**Comment by lramos15** [comment]
We do not at this time, but it's good feedback
