### ISSUE TITLE
Copying feature does not seem to work

### ISSUE THREAD

**Issue by BlazingArdor** [microsoft/vscode-hexeditor#532]
Type: <b>Bug</b>

When copying either bytes or decoded text using the context menu or Ctrl + C, the clipboard text is not set and still retains the previous value

Extension version: 1.10.0
VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (5.76GB free)|
|Process Argv|--crash-reporter-id 047b25f2-73fa-4e91-8e55-e80da2a5ac59|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccplt:31103426
pythonrstrctxt:31103193
wkspc-onlycs-t:31106322

```

</details>

**Comment by dihambo** [comment]
The default copy format is either UTF-8 or Base64. If the "Copy As..." feature is unavailable, you might try compiling the source code from GitHub. After compiling, replace the "dist" directory in your local VS Code extension (located at ~/.vscode/extensions/...hexeditor.../dist) with the newly generated output. Additionally, replace package.json and package.nls.json with the versions from GitHub.

**Comment by connor4312** [comment]
Publishing in https://github.com/microsoft/vscode-hexeditor/pull/541
