### ISSUE TITLE
I want copy the hex not string

### ISSUE THREAD

**Issue by Antecer** [microsoft/vscode-hexeditor#537]
![Image](https://github.com/user-attachments/assets/0ce1f06a-6aa7-4b60-a499-14d8c06f3b66)

like the image, i want copy the selected data to:
"00 98 01 20 A5 14 00 08 1D 16 00 08 21 16 00 08"
not
"AJgBIKUUAAgdFgAIIRYACA=="

**Comment by dihambo** [comment]
我看了一下，这个是vscode市场上的包没正确更新导致的。表面写的是10版本，其实不是。从package.json的内容就可以看出两边的内容不一样，从市场上安装的没有copyas这个命令。你可以clone这个项目然后自己编译，把生成的dist文件夹替换本地扩展的dist，另外把package也改一下，之后就可以复制多种格式了。

**Comment by Antecer** [comment]
> 我看了一下，这个是vscode市场上的包没正确更新导致的。表面写的是10版本，其实不是。从package.json的内容就可以看出两边的内容不一样，从市场上安装的没有copyas这个命令。你可以clone这个项目然后自己编译，把生成的dist文件夹替换本地扩展的dist，另外把package也改一下，之后就可以复制多种格式了。

尝试了一下编译，`vsce package` 给我报了个错误： The `punycode` module is deprecated.
有没有编译好的 vsix 文件分享下？

**Comment by dihambo** [comment]
> > 我看了一下，这个是vscode市场上的包没正确更新导致的。表面写的是10版本，其实不是。从package.json的内容就可以看出两边的内容不一样，从市场上安装的没有copyas这个命令。你可以clone这个项目然后自己编译，把生成的dist文件夹替换本地扩展的dist，另外把package也改一下，之后就可以复制多种格式了。
> 
> 尝试了一下编译，`vsce package` 给我报了个错误： The `punycode` module is deprecated.
> 有没有编译好的 vsix 文件分享下？

这个vsix不知道是用什么打包的。正常来说npm安装完依赖直接就可以编译的

**Comment by Antecer** [comment]
![Image](https://github.com/user-attachments/assets/2944127a-e6f3-42cb-929f-31b64380a59e)
编译不了

**Comment by dihambo** [comment]
你事先用npm编译了吗？
![Image](https://github.com/user-attachments/assets/b58754eb-493c-449f-afdc-cc6eaff44c32)
我之后用vsce打包是成功的
![Image](https://github.com/user-attachments/assets/b6ad03cd-d7a4-4873-ac47-817d32561ce6)

**Comment by Antecer** [comment]
不行，我这里还是报上面那个错误。
你打包成功了，就分享下扩展包呗。

**Comment by dihambo** [comment]
[](https://github.com/dihambo/vscode-hexeditor/releases/tag/1.10.1-beta)

**Comment by Antecer** [comment]
> [hexeditor-1.10.1-beta](https://github.com/dihambo/vscode-hexeditor/releases/tag/1.10.1-beta)

尝试了下添加vsix后缀，然后进行安装，失败了：
```
2024/10/30, 星期三 14:03:52 - Microsoft VSIX Installer
2024/10/30, 星期三 14:03:52 - -------------------------------------------
2024/10/30, 星期三 14:03:52 - vsixinstaller.exe version:
2024/10/30, 星期三 14:03:52 - 17.11.435+d5e02aaeb0
2024/10/30, 星期三 14:03:52 - -------------------------------------------
2024/10/30, 星期三 14:03:52 - Command line parameters:
2024/10/30, 星期三 14:03:52 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,R:\1.10.1-beta.vsix
2024/10/30, 星期三 14:03:52 - -------------------------------------------
2024/10/30, 星期三 14:03:52 - Microsoft VSIX Installer
2024/10/30, 星期三 14:03:52 - -------------------------------------------
2024/10/30, 星期三 14:03:53 - Initializing Install...
2024/10/30, 星期三 14:03:53 - 正在搜索适用的产品...
2024/10/30, 星期三 14:03:55 - System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: 此文件不是有效的 VSIX 包。 ---> System.IO.FileFormatException: 文件包含损坏的数据。
   在 MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
   在 MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   在 MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)
   在 MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   在 System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   在 System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   在 Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   --- 内部异常堆栈跟踪的结尾 ---
   在 Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   在 Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   在 System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   在 VSIXInstaller.ExtensionEngineFactoryForSku.GetTypeFromEngine[TInterface](SupportedVSSKU sku, String typeName, Object[] constructorArguments)
   在 VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   在 VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   在 VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()

```

**Comment by Antecer** [comment]
> [hexeditor-1.10.1-beta](https://github.com/dihambo/vscode-hexeditor/releases/tag/1.10.1-beta)

不行，安装失败：
```
2024/10/30, 星期三 14:06:16 - Microsoft VSIX Installer
2024/10/30, 星期三 14:06:16 - -------------------------------------------
2024/10/30, 星期三 14:06:16 - vsixinstaller.exe version:
2024/10/30, 星期三 14:06:16 - 17.11.435+d5e02aaeb0
2024/10/30, 星期三 14:06:16 - -------------------------------------------
2024/10/30, 星期三 14:06:16 - Command line parameters:
2024/10/30, 星期三 14:06:16 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,R:\hexeditor-1.10.1-beta.vsix
2024/10/30, 星期三 14:06:16 - -------------------------------------------
2024/10/30, 星期三 14:06:16 - Microsoft VSIX Installer
2024/10/30, 星期三 14:06:16 - -------------------------------------------
2024/10/30, 星期三 14:06:17 - Initializing Install...
2024/10/30, 星期三 14:06:17 - 正在搜索适用的产品...
2024/10/30, 星期三 14:06:19 - System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: 元素“Identity”的属性“Version”值无效 ---> System.FormatException: 输入字符串的格式不正确。
   在 System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   在 System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   在 System.Version.TryParseVersion(String version, VersionResult& result)
   在 System.Version.Parse(String input)
   在 System.Version..ctor(String version)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__86_1(String s)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   --- 内部异常堆栈跟踪的结尾 ---
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
   在 Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   在 Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   在 System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   在 VSIXInstaller.ExtensionEngineFactoryForSku.GetTypeFromEngine[TInterface](SupportedVSSKU sku, String typeName, Object[] constructorArguments)
   在 VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   在 VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   在 VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()

```

**Comment by dihambo** [comment]
> > [hexeditor-1.10.1-beta](https://github.com/dihambo/vscode-hexeditor/releases/tag/1.10.1-beta)
> 
> 不行，安装失败：
> ```
> 2024/10/30, 星期三 14:06:16 - Microsoft VSIX Installer
> 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> 2024/10/30, 星期三 14:06:16 - vsixinstaller.exe version:
> 2024/10/30, 星期三 14:06:16 - 17.11.435+d5e02aaeb0
> 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> 2024/10/30, 星期三 14:06:16 - Command line parameters:
> 2024/10/30, 星期三 14:06:16 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,R:\hexeditor-1.10.1-beta.vsix
> 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> 2024/10/30, 星期三 14:06:16 - Microsoft VSIX Installer
> 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> 2024/10/30, 星期三 14:06:17 - Initializing Install...
> 2024/10/30, 星期三 14:06:17 - 正在搜索适用的产品...
> 2024/10/30, 星期三 14:06:19 - System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: 元素“Identity”的属性“Version”值无效 ---> System.FormatException: 输入字符串的格式不正确。
>    在 System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
>    在 System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
>    在 System.Version.TryParseVersion(String version, VersionResult& result)
>    在 System.Version.Parse(String input)
>    在 System.Version..ctor(String version)
>    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__86_1(String s)
>    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
>    --- 内部异常堆栈跟踪的结尾 ---
>    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
>    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
>    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
>    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
>    在 Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
>    在 Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
>    --- 内部异常堆栈跟踪的结尾 ---
>    在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    在 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
>    在 System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    在 System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    在 VSIXInstaller.ExtensionEngineFactoryForSku.GetTypeFromEngine[TInterface](SupportedVSSKU sku, String typeName, Object[] constructorArguments)
>    在 VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
>    在 VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
>    在 VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
>    在 VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
>    在 VSIXInstaller.App.Initialize(Boolean isRepairSupported)
>    在 VSIXInstaller.App.Initialize()
>    在 System.Threading.Tasks.Task`1.InnerInvoke()
>    在 System.Threading.Tasks.Task.Execute()
> 
> ```

呃，我这个是vsc插件，不是VS的

**Comment by Antecer** [comment]
> > > [hexeditor-1.10.1-beta](https://github.com/dihambo/vscode-hexeditor/releases/tag/1.10.1-beta)
> > 
> > 
> > 不行，安装失败：
> > ```
> > 2024/10/30, 星期三 14:06:16 - Microsoft VSIX Installer
> > 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> > 2024/10/30, 星期三 14:06:16 - vsixinstaller.exe version:
> > 2024/10/30, 星期三 14:06:16 - 17.11.435+d5e02aaeb0
> > 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> > 2024/10/30, 星期三 14:06:16 - Command line parameters:
> > 2024/10/30, 星期三 14:06:16 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,R:\hexeditor-1.10.1-beta.vsix
> > 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> > 2024/10/30, 星期三 14:06:16 - Microsoft VSIX Installer
> > 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> > 2024/10/30, 星期三 14:06:17 - Initializing Install...
> > 2024/10/30, 星期三 14:06:17 - 正在搜索适用的产品...
> > 2024/10/30, 星期三 14:06:19 - System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: 元素“Identity”的属性“Version”值无效 ---> System.FormatException: 输入字符串的格式不正确。
> >    在 System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
> >    在 System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
> >    在 System.Version.TryParseVersion(String version, VersionResult& result)
> >    在 System.Version.Parse(String input)
> >    在 System.Version..ctor(String version)
> >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__86_1(String s)
> >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
> >    --- 内部异常堆栈跟踪的结尾 ---
> >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
> >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
> >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
> >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
> >    在 Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
> >    在 Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
> >    --- 内部异常堆栈跟踪的结尾 ---
> >    在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
> >    在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> >    在 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
> >    在 System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
> >    在 System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
> >    在 VSIXInstaller.ExtensionEngineFactoryForSku.GetTypeFromEngine[TInterface](SupportedVSSKU sku, String typeName, Object[] constructorArguments)
> >    在 VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
> >    在 VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
> >    在 VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
> >    在 VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
> >    在 VSIXInstaller.App.Initialize(Boolean isRepairSupported)
> >    在 VSIXInstaller.App.Initialize()
> >    在 System.Threading.Tasks.Task`1.InnerInvoke()
> >    在 System.Threading.Tasks.Task.Execute()
> > ```
> 
> 呃，我这个是vsc插件，不是VS的


好吧，是我乌龙了。直接双击安装被VS接管了，然后就提示版本号命名不符合规则。
然后我还zip拆包给版本号后面的beta删了，再双击安装，才被提示该插件用于vscode，需要在vscode内安装。
于是我给它直接拖入vscode，成功安装了。

然后，还有个问题，虽然能复制hex了，但是得到的结果是没有空格的，与选择界面中被选中的状态有差别，有没有办法保留空格，让数据按空格分隔byte？

**Comment by dihambo** [comment]
> > > > [hexeditor-1.10.1-beta](https://github.com/dihambo/vscode-hexeditor/releases/tag/1.10.1-beta)
> > > 
> > > 
> > > 不行，安装失败：
> > > ```
> > > 2024/10/30, 星期三 14:06:16 - Microsoft VSIX Installer
> > > 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> > > 2024/10/30, 星期三 14:06:16 - vsixinstaller.exe version:
> > > 2024/10/30, 星期三 14:06:16 - 17.11.435+d5e02aaeb0
> > > 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> > > 2024/10/30, 星期三 14:06:16 - Command line parameters:
> > > 2024/10/30, 星期三 14:06:16 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,R:\hexeditor-1.10.1-beta.vsix
> > > 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> > > 2024/10/30, 星期三 14:06:16 - Microsoft VSIX Installer
> > > 2024/10/30, 星期三 14:06:16 - -------------------------------------------
> > > 2024/10/30, 星期三 14:06:17 - Initializing Install...
> > > 2024/10/30, 星期三 14:06:17 - 正在搜索适用的产品...
> > > 2024/10/30, 星期三 14:06:19 - System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: 元素“Identity”的属性“Version”值无效 ---> System.FormatException: 输入字符串的格式不正确。
> > >    在 System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
> > >    在 System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
> > >    在 System.Version.TryParseVersion(String version, VersionResult& result)
> > >    在 System.Version.Parse(String input)
> > >    在 System.Version..ctor(String version)
> > >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__86_1(String s)
> > >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
> > >    --- 内部异常堆栈跟踪的结尾 ---
> > >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
> > >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
> > >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
> > >    在 Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
> > >    在 Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
> > >    在 Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
> > >    --- 内部异常堆栈跟踪的结尾 ---
> > >    在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
> > >    在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> > >    在 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
> > >    在 System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
> > >    在 System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
> > >    在 VSIXInstaller.ExtensionEngineFactoryForSku.GetTypeFromEngine[TInterface](SupportedVSSKU sku, String typeName, Object[] constructorArguments)
> > >    在 VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
> > >    在 VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
> > >    在 VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
> > >    在 VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
> > >    在 VSIXInstaller.App.Initialize(Boolean isRepairSupported)
> > >    在 VSIXInstaller.App.Initialize()
> > >    在 System.Threading.Tasks.Task`1.InnerInvoke()
> > >    在 System.Threading.Tasks.Task.Execute()
> > > ```
> > 
> > 呃，我这个是vsc插件，不是VS的
> 
> 
> 好吧，是我乌龙了。直接双击安装被VS接管了，然后就提示版本号命名不符合规则。
> 然后我还zip拆包给版本号后面的beta删了，再双击安装，才被提示该插件用于vscode，需要在vscode内安装。
> 于是我给它直接拖入vscode，成功安装了。
> 
> 然后，还有个问题，虽然能复制hex了，但是得到的结果是没有空格的，与选择界面中被选中的状态有差别，有没有办法保留空格，让数据按空格分隔byte？
> 

你可以自己做开发，或者用正则。另外里面有copyas这个特性，你可以自己选。
复制格式可设置这个我在开发，issue我也提了。不过你这个特性我暂不打算支持，因为开发中跟代码并不很适配。

**Comment by Antecer** [comment]
其实我说的这个复制格式，在一个叫 `hexdump for VSCode` 的插件支持的，我觉得它的复制方式就比较符合人类直觉。
比如，在hex区复制出来就是 hex 字符串。 在右边的ascii区复制出来就是ascii字符串。

不过，你开发的这个copyas，确实很方便，可以自由实现任意格式。
所以，建议弄个自定义正则表达式的配置项，然后用户就可以根据需求自己写正则表达式来 copyas 自己需要的格式了。

**Comment by dihambo** [comment]
> 其实我说的这个复制格式，在一个叫 `hexdump for VSCode` 的插件支持的，我觉得它的复制方式就比较符合人类直觉。
> 比如，在hex区复制出来就是 hex 字符串。 在右边的ascii区复制出来就是ascii字符串。
> 
> 不过，你开发的这个copyas，确实很方便，可以自由实现任意格式。
> 所以，建议弄个自定义正则表达式的配置项，然后用户就可以根据需求自己写正则表达式来 copyas 自己需要的格式了。
> 
> 顺便一提，之所以会用到 byte{空格}byte 的格式，是因为需要用在串口工具上，这样比较方便。

澄清一下，copyas这个不是我开发的，之前就有。只不过似乎因为打包问题市场上的插件一直没更新出来。我只是重新编译打包了一下，让其恢复正常。
你说的功能确实不错，但是需要我抽业余时间做。不会很快更新。

**Comment by Antecer** [comment]
重新折腾了一下，给package.json添加了一个空数组 `"activationEvents": [],` 就打包通过了

**Comment by Antecer** [comment]
添加一个所见即所得的copyas 还是很容易的，已经提交 PR 了
