### ISSUE TITLE
Market version and GitHub source version mismatch: missing "Copy As..." and related features in VS Code Marketplace extension

### ISSUE THREAD

**Issue by dihambo** [microsoft/vscode-hexeditor#538]
I've observed a discrepancy between the VS Code Marketplace version of the extension and the version on GitHub. Using package.json as a reference, I found that the GitHub version includes the "Copy As..." feature as well as related functionalities like "Copy Offset as Hex." However, the Marketplace version installed locally lacks these commands and features.

To confirm, I compiled the source code from GitHub, replaced the dist folder in my local extension directory with the newly compiled output, and reloaded the extension. After this, all previously missing features, including "Copy As..." and "Copy Offset as Hex," became available. This seems to indicate that the current Marketplace package may not be fully aligned with the GitHub source and may have missed some feature updates during the packaging or publishing process.

Could you please verify that the Marketplace version includes all recent updates from GitHub, and ensure that all intended features are packaged correctly?

Thank you for your attention to this issue.

**Comment by connor4312** [comment]
publishing in https://github.com/microsoft/vscode-hexeditor/pull/541
