### ISSUE TITLE
Enhancement Request: Make `doCopy` function copy format configurable via `defaultCopyFormat` setting

### ISSUE THREAD

**Issue by dihambo** [microsoft/vscode-hexeditor#539]
Currently, the `doCopy` function only supports copying in UTF-8 or Base64 formats. However, with the recent addition of the "Copy As..." feature, several additional formats are now available. It would be beneficial if the `doCopy` function's default copy format could be configured to use one of these formats through a new setting, such as `defaultCopyFormat`.

This enhancement would allow users to set their preferred default copy format without needing to use "Copy As..." each time, making workflows more flexible and efficient. Thank you for considering this feature request, and I look forward to seeing this improvement!

**Comment by Antecer** [comment]
我已经添加了一个名为 `Copy Type` 的选项作为默认的 拷贝 格式，并已提交PR，静待审核。

**Comment by dihambo** [comment]
> 我已经添加了一个名为 `Copy Type` 的选项作为默认的 拷贝 格式，并已提交PR，静待审核。

辛苦了👍
