### ISSUE TITLE
Nothing displays in window in v1.11.0

### ISSUE THREAD

**Issue by zhengyang-lu** [microsoft/vscode-hexeditor#551]
After upgrading the extension to v1.11.0, nothing displays after opening a file.

OS: Windows 11 Pro 23H2
VS Code: 1.95.1

https://github.com/user-attachments/assets/10ea8e97-c372-4578-aaf8-ba14543ac4b2

**Comment by toolsmanhehe** [comment]
I also encountered the same problem today, I can't open the bin file, it's blank

**Comment by BC-548** [comment]
I have also been having this problem, on MacOS.

**Comment by jogo-** [comment]
Duplicates #546 #547

**Comment by PTT3108** [comment]
![Image](https://github.com/user-attachments/assets/5f14052f-5da5-4e18-b20b-91dd4b373725)
I also had the same problem

**Comment by ARNik** [comment]
The same problem. 
Have to downgrade the extension to 1.10.0 version.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-hexeditor/issues/547
