### ISSUE TITLE
lexicographically sort "Compare Selected" options

### ISSUE THREAD

**Issue by mfulton26** [microsoft/vscode-hexeditor#560]
When I select two files in the file explorer and right click I get the option to "Compare Selected" _after_ the new option to "Compare Selected in HexEditor (Experimental)". Lexicographically speaking, "Compare Selected" should bo ordered _before_ "Compare Selected in HexEditor (Experimental)". Can we get the order updated so that "Compare Selected" doesn't "move" on me. I was surprised when the new option showed up and I keep wanting to click the wrong one from muscle memory.

![Image](https://github.com/user-attachments/assets/bcc31f4c-1cd4-4242-92b7-1cdb67a2e5c4)

**Comment by tomilho** [comment]
Let me see if I can switch the order and I'll make a PR.
