### ISSUE TITLE
Remove the "Max file size" setting / change the validation message

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode-hexeditor#58]
Testing https://github.com/microsoft/vscode/issues/101307

Based in the release notes, we got rid of the 18M file restriction in v1.1.0.

The setting should either be removed, or the validation message should be fixed

![Screenshot_20200630_153327](https://user-images.githubusercontent.com/8235156/86169155-32294a80-bae7-11ea-892d-fec8bb520d56.png)

**Comment by lramos15** [comment]
[hexeditor-1.1.0.zip](https://github.com/microsoft/vscode-hexeditor/files/4854188/hexeditor-1.1.0.zip)
Fixed. Here's a new vsix.
