### ISSUE TITLE
The "HexEditor: Open file" command does not work if text editor is not open

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode-hexeditor#59]
Testing https://github.com/microsoft/vscode/issues/101307

Is there an easier way to open large files?

Update:
I can still open the file using "View: Reopen editor with > HexEditor". But the "HexEditor: Open file" command does work. At least not on linux :sweat_smile: 

![hexeditor](https://user-images.githubusercontent.com/8235156/86180324-e2a04a00-baf9-11ea-9460-d0e0a78250a4.gif)

**Comment by lramos15** [comment]
I'll leave this open to track the bug, but this involves VS Code implementing an API which allows me to retrieve the URI of the active tab. Therefore the fix for this is blocked until then.

**Comment by skmaidul786** [comment]
Open directory failed binary execution error

**Comment by connor4312** [comment]
We removed this command.
