### ISSUE TITLE
Linux: Weird lines in the data inspector

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode-hexeditor#60]
Testing https://github.com/microsoft/vscode/issues/101307

![Screenshot_20200630_181453](https://user-images.githubusercontent.com/8235156/86182505-1d0be600-bafe-11ea-8920-bbd3373ddc7e.png)

I don't know what's causing it. It's visible on both my QHD, and FHD monitors on linux. I have tried the following things:
- reloading vscode
- restarting vscode
- starting vscode with `--disable-gpu`

**Comment by lramos15** [comment]
This is caused by there being a slight gap between the input boxes and that's the background of the editor seeping in. I'm unsure of the best way to fix this, but I have seen it a couple of times.
