### ISSUE TITLE
Undo is not updating the source

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-hexeditor#63]
Testing https://github.com/microsoft/vscode/issues/101307

- Open Hex editor
- Do a change
- Go to SCM view and make sure the file is shown as changed
- Undo the change
🐛 File is still shown changed in SCM view

**Comment by lramos15** [comment]
Are you saving after the undo?

**Comment by sandy081** [comment]
I am sorry to mention that Auto save is enabled, so I expect undo shall save it.

**Comment by lramos15** [comment]
Fixed in https://github.com/microsoft/vscode-hexeditor/pull/85
