### ISSUE TITLE
Hex editor is not recognising stale change and overriding on save

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-hexeditor#64]
Testing https://github.com/microsoft/vscode/issues/101307

- Have auto save disabled
- Open a file using Hex Editor and normally side by side
- Do a change in Hex Editor
- Do a change in normal file and save
- Save the change in Hex Editor
🐛 It is overriding the change made in Normal file. Instead it shall show a conflict.

**Comment by lramos15** [comment]
If I understand correctly, #64 and #62 are similar issues. I believe this is caused by a lack of a file watcher.

**Comment by sandy081** [comment]
Not sure if the underlying root cause is same or not.
