### ISSUE TITLE
Hex editor - selected cell should have consistent style

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-hexeditor#66]
Testing https://github.com/microsoft/vscode/issues/101307

Selected cell in the `Decoded Text` pane should also have a border. 

![image](https://user-images.githubusercontent.com/3372902/86253288-a2ea6880-bbb4-11ea-9b89-531e270f11c7.png)

**Comment by lramos15** [comment]
That border is the focus border, it's showing you that you have the hex cell focused and not the decoded text. If you were to click the data inspector and have it lose focus you should see that both the styles are the same.
