### ISSUE TITLE
Click and drag behavior is weird

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-hexeditor#7]
Testing https://github.com/microsoft/vscode/issues/98980

I get the feeling that the UI is stuck every time I click & drag... nothing really happens. I expected a range cursor a la text editor

**Comment by lramos15** [comment]
We currently only support editing a single cell at a time and only deleting cells at the end of the file. What would you expect to happen after I selected a bunch of cells and press "AA" for example.

**Comment by joaomoreno** [comment]
Two options:

- Have the current cell cursor move until the user releases the mouse
- Simply ignore the selection once the user starts typing

HxD seems to do the latter, since there are features around selecting ranges of bytes:

![recording](https://user-images.githubusercontent.com/22350/86046721-0443f780-ba4e-11ea-9b72-72320437f8d7.gif)

I would go with the former, since we have no such features for now. Right now it just feels _weird_ that I hold the mouse down and move and nothing happens.
