### ISSUE TITLE
Feature Request: Default for endianness via settings

### ISSUE THREAD

**Issue by haneefdm** [microsoft/vscode-hexeditor#72]
Very few people use BE, but they exist. I don't even want to get into the bit-endianness. So long as we have an "Endianness" setting in the UI, why not have a default

Added bonus would be to save the setting on a per-file basis. I know I am asking for too much.

**Comment by lramos15** [comment]
We might want to implement a settings service to easily support more settings as more get requested as there currently is only one setting and it's kind of just thrown in there. 
The question also arises should little endian appear first on the dropdown because it's more commong in x86 systems.

**Comment by haneefdm** [comment]
Yes. FYI: Little Endian is already the first (and default) for me. I will double-check. x86 is LE. While ARM devices are configurable for endian-ness, the default/most-prevalent choice is LE. Even RISC-V is LE

I ran into a couple of ARM users using BE and not sure why they chose that, so much Firmware/Software could break -- no one tests for BE anymore (can't find HW easily).

But I am glad you have that option in hexEditor

**Comment by lramos15** [comment]
Ah yes. Little endian is already the default. I was just going based off of memory. I know endianness is still important in C's network library. If you would like to add the setting it shouldn't be too much more work, just need to choose which one is selected by default. I'm not sure the per file thing would be necessary as it feels over engineered to me, but maybe others will chime in and state they would like that feature as well.

**Comment by haneefdm** [comment]
Yeah, I agree per file is not needed. It is more of a workspace/user setting.

**Comment by connor4312** [comment]
This is now configurable via `hexEditor.defaultEndianness`
