### ISSUE TITLE
file changes are neglected

### ISSUE THREAD

**Issue by JHenneberg** [microsoft/vscode-hexeditor#74]
Hello,

once the file is loaded into the editor it is not realising any update on the file. Therefore the file needs to be manually closed and opened again.

**Comment by lramos15** [comment]
Yes I believe this all links back into the fact that there is no filewatcher run. This is something I plan to look into for the july iteration. It's very similar to #63 and #62

**Comment by JHenneberg** [comment]
Sounds very good. VSC is missing a decent hex editor.
