### ISSUE TITLE
Click and Drag Selection does not shrink

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-hexeditor#78]
If you click and drag to create a selection the selection can only get bigger not smaller. If you attempt to drag the selection smaller nothing happens. [Code Pointer](https://github.com/microsoft/vscode-hexeditor/blob/master/media/virtualDocument.ts#L130)

**Comment by jeanp413** [comment]
Created a PR https://github.com/microsoft/vscode-hexeditor/pull/92 that fixes this
