### ISSUE TITLE
Revert File actually works but display is not updated

### ISSUE THREAD

**Issue by haneefdm** [microsoft/vscode-hexeditor#79]
Okay, I am not sure how or why. I went through the following sequence

* Edit a byte (now I see the modified flag in the tab for the editor). I have a visual indication of the new byte
* I do a 'File->Revert File' from the menu. The flag disappears but the data and the display in the editor window is unchanged
* I switch to any other random tab/editor and come back to the original. It has totally refreshed. Edits are lost, which is fine 'cause that is normal VSCode behavior for me for any other editor.

I expect the display to be updated when 'Revert File' is chosen. In a way, the document has been updated but the view(s) isn't.

I can look into a fix for this later but I just wanted to report it and move on. Perhaps this is work in progress or intentional or both at this point.

When I say flag, I mean that little dot next to file-name
![image](https://user-images.githubusercontent.com/41269583/87175454-84a7fb00-c28d-11ea-9c2c-a2d18f3240a8.png)

**Comment by lramos15** [comment]
Yeah it's because some of the code is there for revert as it was needed to get the document to compile, but the actual functionality isn't there. I will be working on it today and monday. See https://github.com/microsoft/vscode-hexeditor/tree/revert
