### ISSUE TITLE
Binary templates

### ISSUE THREAD

**Issue by Trass3r** [microsoft/vscode-hexeditor#80]
I guess this is a non-goal for this extension but just for the fun of it I'll mention it here.
https://www.sweetscape.com/010editor/templates.html
This is a killer feature.

**Comment by lramos15** [comment]
Is this similar to #50?

**Comment by Trass3r** [comment]
Yes looks like it, though I've never heard of Kaitai.

**Comment by lramos15** [comment]
Ok I'll close this and use #50 to track general binary template feature request then.
