### ISSUE TITLE
Losing data inspector when switching editors

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-hexeditor#81]
Issue Type: <b>Bug</b>

1) open file
2) reopen with hex editor
3) switch to tab (with settings editor)
4) swicth back to hexeditor tab
-> data inspector values are now empty

Extension version: 1.1.0
VS Code version: Code - Insiders 1.48.0-insider (e7920dce7bfd0b707ebfc0a5379c6edd2233e475, 2020-07-10T11:55:11.286Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.3.0-1020-azure

**Comment by EmbeddedBacon** [comment]
I see something similar to this, but after 3-5 seconds switching back to the Data Inspector data is shown again.

**Comment by lramos15** [comment]
Upstream issue, fixed by https://github.com/microsoft/vscode/commit/25adee245fcd9f2af2af44fbf628274b0f46ffcd
