### ISSUE TITLE
Not available on Open VSX registry

### ISSUE THREAD

**Issue by kroppt** [microsoft/vscode-hexeditor#82]
VSCodium currently uses the [Open VSX Registry](https://open-vsx.org/) as its default marketplace. I suggest publishing to this along with publishing to the Microsoft Visual Studio Marketplace for releases.
I know this is like contributing to your competitor or whatever, but it is open source, so there's that.
Thanks.

**Comment by lramos15** [comment]
Being a Microsoft extension we will only be published to  the Microsoft marketplace. You can always pull the VSIX from the marketplace if you would like to continue using codium.
