### ISSUE TITLE
Instant navigation to specified point in file

### ISSUE THREAD

**Issue by JordanLongstaff** [microsoft/vscode-hexeditor#83]
I wish to have the ability to enter in an exact location in hexadecimal and instantly navigate to that location in a file. For example, entering `A1B2` instantly moves the cursor to byte `0xA1B2` of the file.

**Comment by Lisoph** [comment]
Similarly, being able to click on a button in the data inspector and landing at the address represented by any of the integers, would be nice. I think that would be very useful for finding offsets.

**Comment by lramos15** [comment]
Resolved with #203
