### ISSUE TITLE
Data Inspector promises UTF-8 decoding, but actually shows CP-1252 decoding

### ISSUE THREAD

**Issue by tullo-x86** [microsoft/vscode-hexeditor#84]
The Data Inspector view claims to be decoding UTF-8, but appears to be interpreting byte sequences as if they were simply CP-1252 characters. [UTF-8 allows for the escaping of byte sequences](https://tools.ietf.org/html/rfc3629#section-3) to represent code points which don't fit in the range `00`-`7F` using a byte with the high bit set to `1`. This extension appears to ignore all that.

If decoding UTF-8 sequences sounds beyond the scope of a hex editor, it may be prudent to instead simply label the decoding as "CP-1252" instead of pretending to support UTF-8.

### Examples

1. Byte order mark `U+FEFF` (a single code point) encoded in UTF-8 (`EF` `BB` `BF`) interpreted as the character sequence `ï»¿`:
![image](https://user-images.githubusercontent.com/2888110/87331188-37cb5b00-c4ff-11ea-9c71-5aa5c80695fa.png)

2. `U+2642 MALE SIGN` decoded incorrectly as UTF-8 (but correctly as UTF-16):
![image](https://user-images.githubusercontent.com/2888110/87330156-baebb180-c4fd-11ea-9276-69efe4feff3c.png)

**Comment by lramos15** [comment]
Thank you for pointing this out. I will be investigating this and hope to get proper UTF-8 decoding for the August release.

**Comment by tullo-x86** [comment]
And here I was thinking that would be out of scope! Consider whether it might be worthwhile to both print the character at that code point as well as its Unicode notation and name, e.g. `🤷 U+1F937 SHRUG`.

You'll probably want to stop there, since venturing any further into "grapheme cluster" territory gets tricky.

That said, if you _were_ determined to list out the code points for 👨‍👩‍👧‍👦 (which, for reference, are `👨‍ U+1F468 MAN`, `U+200D ZERO WIDTH JOINER`, `👩 U+1F469 WOMAN`, `U+200D ZERO WIDTH JOINER`, `👧 U+1F467 GIRL`, `U+200D ZERO WIDTH JOINER`, `👦 U+1F466 BOY`), I wouldn't dream of stopping you.

**Comment by lramos15** [comment]
For this iteration I'll probably limit it to just proper character rendering as we don't do anything fancier than that for UTF-16.
