### ISSUE TITLE
Display offset

### ISSUE THREAD

**Issue by TanukiSharp** [microsoft/vscode-hexeditor#86]
Offset of first selected byte should be display.
Maybe in the status below like for other languages, or in the Data inspector.

**Comment by lramos15** [comment]
So you wan't the data inspector to also show an offset different from one is in the column on the side of the hex section

**Comment by TanukiSharp** [comment]
Yes, basically the sum of line offset + column offset. Not something impossible to do by the user, but for the ones working day and night in binary data, this could be of a great help.

Like the blue I added on the screenshot below:
![image](https://user-images.githubusercontent.com/4018313/87502793-86166080-c69d-11ea-8eb6-6a91337ec312.png)

Could also be in the status bar like for other lanugages:
![image](https://user-images.githubusercontent.com/4018313/87502873-c4ac1b00-c69d-11ea-8649-1ec2d6dc5055.png)

But I think it would be easier to find quickly in the Data Inspector pane, and there is plenty of empty space anyway :)

Thanks for your consideration.

**Comment by lramos15** [comment]
So the reason I'm trying to avoid putting read only values in data inspector is due to eventually wanting to support editing the values in the data inspector as well. I will take the status bar into consideration.

**Comment by EDais** [comment]
+1 With regards to not wanting to add static values to the data inspector, it would be extremely useful to be able to edit the offset and have the caret jump to the new offset.

**Comment by lramos15** [comment]
> it would be extremely useful to be able to edit the offset and have the caret jump to the new offset.

@EDais we already have support for F1 -> Go to offset.

**Comment by TanukiSharp** [comment]
If the problem is really mixing editable and non-editable fields in the data inspector, I'm really fine with that.
So it could either be like @EDais suggested and be editable (alongside with F1 feature) or in the data inspector in a sub-section specifically tagged "Non editable", or the status bar, I don't really mind where and how, as long as this easily accessible.

Thank you for your consideration.

**Comment by wad8989** [comment]
It's weird that you support "Go to offset", but not display an offset for us to go to 🤣

**Comment by connor4312** [comment]
This can be added in the activity bar badge being worked on in https://github.com/microsoft/vscode-hexeditor/pull/349

**Comment by shaperilio** [comment]
> > it would be extremely useful to be able to edit the offset and have the caret jump to the new offset.
> 
> @EDais we already have support for F1 -> Go to offset.

Why not CTRL+G like "go to line number"?

**Comment by connor4312** [comment]
@shaperilio how are you thinking that'd differ from the existing Go to Offset command? Are you just looking for a default keybinding?

**Comment by shaperilio** [comment]
> > it would be extremely useful to be able to edit the offset and have the caret jump to the new offset.
> 
> @EDais we already have support for F1 -> Go to offset.

And also CTRL+G, which is a nice parallel.

I vote strongly *against* putting the offset in the status bar. If I'm in the hex editor and looking at values in the Data Inspector, I don't want to have to move my gaze all the way to a tiny status bar to find a cursor position.

If editability is a concern, then A) allow the offset to be editable like @EDais or B) make editable fields be inside "text boxes".

In my particular use case, I'm diagnosing binary file IO, so as I step through my code, I'm seeing offset in decimal (by hovering the mouse pointer over the variable or putting the variable in the watch list) and then having to go to the hex editor, add two numbers, and convert from hex to decimal...

I'm sure I don't understand the full history of offsets being in hex but I think in this day and age I'd expect to be able to see/specify them in decimal as well to better tie in with e.g. debugging.

**Comment by shaperilio** [comment]
> @shaperilio how are you thinking that'd differ from the existing Go to Offset command? Are you just looking for a default keybinding?

Sorry, I realized I misspoke and deleted my comment, but I think you had already replied. See below.

**Comment by TanukiSharp** [comment]
If it is made a non-editable field in the data inspector, please make sure it is still selectable for copy/paste (read-only textbox, not a label). I'm just saying ;)

**Comment by connor4312** [comment]
I've some conviction that we should keep the offset in the status bar and use the same overall semantics as text editors for the hex editor. So, to @TanukiSharp's comment, clicking on the position in the status bar would open the "Go to Offset" quick input. But maybe if someone has an idea for a UI where showing the current offset elsewhere is pleasant and unobtrusive, I could be convinced otherwise 🙂

**Comment by shaperilio** [comment]
> I've some conviction that we should keep the offset in the status bar and use the same overall semantics as text editors for the hex editor.

I think a text editor is, by nature, quite different than a hex editor. In a text editor, your cursor is showing you exactly what you're typing. You don't need to look elsewhere to interpret what a particular character is, so there is literally nowhere else for position to go than the status bar.

A hex editor you can think of as an editor for, say, Kanji, or hieroglyphics, or whatever - for someone who can't read that character set. So on the side you're showing the user some more information as to how to interpret what's at the cursor, and if their eyes are already there, show them cursor position there, too. I think it's fine to *also* have it in the status bar, but I think the data pane is a good central location for "all information which depends on the the cursor position"

And, as @TanukiSharp mentioned, it opens up the possibility to copy and paste its value.

**Comment by shaperilio** [comment]
If anyone wants to try it, [this version](https://github.com/notblank00/vscode-hexeditor) has the offset in the Data Inspector.
