### ISSUE TITLE
Hex section does not support numpad

### ISSUE THREAD

**Issue by TanukiSharp** [microsoft/vscode-hexeditor#87]
Currently (1.1.0) it is not possible to edit in "Memory" view, but only in "Decoded Text" view.

Please add support for hexadecimal edition in the "Memory" view.

**Comment by lramos15** [comment]
You can edit in the decoded text and in the memory view. Can you further explain the issue you're encountering?

**Comment by TanukiSharp** [comment]
Oh you are right, that's because I was trying the numeric pad (numbers at the right on the keyboard) and it was not working.
So I guess it's a different issue.

In Memory pane, the green keys work, the red ones don't (on the picture below)
![image](https://user-images.githubusercontent.com/4018313/87503279-c4604f80-c69e-11ea-846c-f1685e1621fe.png)

I have a standard US mapping keyboard.

Let me know if you want me to close this issue and open a new and better titled one.

**Comment by lramos15** [comment]
I have edited the title and added it to this iteration plan. Thank you for reporting the bug.
