### ISSUE TITLE
Feature Request+BUG: Allow settings to be set inside .code-workspace

### ISSUE THREAD

**Issue by TriMoon** [microsoft/vscode-hexeditor#88]
# Feature Request
The info at [How to Use](https://github.com/microsoft/vscode-hexeditor#how-to-use) mentions settings that can be used in the user's `settings.json` file.
If these settings would be allowed to be put inside a `.code-workspace` also, that would be very handy for repo based code sharing...

# BUG:
The [Requirements](https://github.com/microsoft/vscode-hexeditor#requirements) state that VSC `1.46+` is needed, however the settings mentioned above are dimmed in the editor with the "Unknown Configuration Setting" popup, and they **don't** work.
Here is are snippets of what i used:
- in the user's `settings.json` file:
  ```json
  {
	....
	"workbench.editorAssocations": [
		{
			"filenamePattern": "*.auth",
			"viewType": "hexEditor.hexedit"
		},
		{
			"filenamePattern": "*.esl",
			"viewType": "hexEditor.hexedit"
		}
	],
	....
  }
  ```
- in the `.code-workspace` file:
  ```json
  {
	"settings": {
		....
		"workbench.editorAssocations": [
			{
				"filenamePattern": "*.auth",
				"viewType": "hexEditor.hexedit"
			},
			{
				"filenamePattern": "*.esl",
				"viewType": "hexEditor.hexedit"
			}
		],
		....
	}
  }
  ```

# Used version and OS
```console
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:30:34.302Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-40-generic
```
```console
OS: Ubuntu 20.04 LTS x86_64 
Model: Rev:xxx 
Mainboard: X99-PRO/USB 3.1 Rev 1.xx (ASUSTeK COMPUTER INC.) 
Bios: 2018-04-19 AMI Ver:3902 
Kernel: 5.4.0-40-generic 
Uptime: 7 days, 19 hours, 31 mins 
Packages: 2351 (dpkg) 
Shell: zsh 5.8 
Resolution: 1680x1050 @ 59.88Hz, 2560x1080 @ 60.00Hz 
DE: Plasma 
WM: KWin 
WM Theme: Breeze 
Theme: Breeze Dark [Plasma], Adapta-Nokto [GTK2], Default [GTK3] 
Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
Terminal: vscode 
Font: [Plasma], Noto Sans, 10 [GTK2/3] 
Locale: en_US.UTF-8 
Memory: 10856MiB / 32026MiB (33%) [-----==========] 
CPU: Intel i7-5820K (12) @ 3.6GHz [47.0°C] 
GPU: NVIDIA GeForce GTX 1080 Ti 
GPU Driver: NVIDIA 440.100 
CPU Usage: 7% 
Disk (/): 7.7G / 63G (13%) 
Disk (home): 24G / 63G (41%) 
Disk (efi): 358M / 549M (66%) 
```

**Comment by lramos15** [comment]
Your settings say `workbench.editorAssocations` but it's `workbench.editorAssociations`. You forgot the i.

**Comment by TriMoon** [comment]
> Your settings say `workbench.editorAssocations` but it's `workbench.editorAssociations`. You forgot the i.

Ohh, but it was a copy/paste from the info of extension itself? 😕 
I will try when I get behind my machine, on which I posted this bug,  again and see if that fixes things.
I didn't even notice the spelling 🤣

**Comment by TriMoon** [comment]
@lramos15 
Please correct https://github.com/microsoft/vscode-hexeditor/blame/master/README.md#L26 as that is the cause of my error...

It seems to work now with correction of name :wink:

**Comment by lramos15** [comment]
Ah it was correct everywhere else. I'll fix that right away 😅. It will be updated with the next release
