### ISSUE TITLE
Navigating up/down should only scroll the minimum necessary

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-hexeditor#9]
Testing https://github.com/microsoft/vscode/issues/98980

If you press <kbd>DownArrow</kbd> continuously until you hit the bottom of the page and then some, the view will scroll in a way the cursor will be at the center of the viewport. The view should really only scroll bit by bit, similar to a text editor.

**Comment by lramos15** [comment]
Can you explain this further? I don't see the difference.

**Comment by joaomoreno** [comment]
![recording (12)](https://user-images.githubusercontent.com/22350/83642557-485aee00-a5af-11ea-897d-ccafbfd8302e.gif)

**Comment by lramos15** [comment]
Fixed in #39
