### ISSUE TITLE
When condition and open with text editor command feature request

### ISSUE THREAD

**Issue by DnnMitko** [microsoft/vscode-hexeditor#91]
This extension adds a "HexEditor: Open file" command.
If we get a command that does the same but reopens the file with the Text Editor and a when condition to tell the two states apart, it'll be very comfortable to script different shortcuts like toggle hex view and such.

**Comment by lramos15** [comment]
You can use the toggle editor type command to switch back to the text editor

**Comment by DnnMitko** [comment]
That would work just fine
