### ISSUE TITLE
Bug: Trying to open empty untitled file with the hex editor closes it

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode-hexeditor#93]
Steps to reproduce:

1. Press <kbd>Ctrl</kbd>+<kbd>N</kbd> to create a new untitled file
2. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> to open the command palette and choose "Reopen with" and then choose this hex editor
3. There is an error notification, and the untitled file is forcibly closed.

This also occurs if you enter some text in the untitled file and then delete it, so the text that you could recover by undoing is now gone entirely.

**Comment by lramos15** [comment]
Duplicate of #52
