### ISSUE TITLE
Make editing work with numeric keypad too

### ISSUE THREAD

**Issue by Zastai** [microsoft/vscode-hexeditor#94]
I was initially puzzled by the supposed support for editing, because for me the natural way is to use the numeric keypad for digits, and nothing was happening when I was using those.
However, it looks like the editing only supports digits entered via the main keyboard.

Please add support for the numeric keypad as well.

**Comment by lramos15** [comment]
This is already fixed in master and will be fixed in the next release. See https://github.com/microsoft/vscode-hexeditor/issues/87
