### ISSUE TITLE
Search icons are not vertically centered

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#97]
![image](https://user-images.githubusercontent.com/2193314/88102471-780c8800-cb54-11ea-86b9-1397cffe83dc.png)

**Comment by connor4312** [comment]
Fixed in my rework

<img width="441" alt="image" src="https://user-images.githubusercontent.com/2230985/206589732-4c52ea56-5ce7-46fc-8f5b-d049e614cd19.png">
